<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Agreement;
use App\Models\Institution;
use App\Models\AgreementType;
use Illuminate\Support\Facades\DB;

class Convenios2021Seeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // 1. Crear los 3 tipos de alianza oficiales
        $tipos = [
            'marco' => AgreementType::firstOrCreate(['name' => 'Convenio Marco']),
            'especifico' => AgreementType::firstOrCreate(['name' => 'Convenio Específico']),
            'memorando' => AgreementType::firstOrCreate(['name' => 'Memorando de Entendimiento']),
        ];
        
        // Estructura: [0: Código, 1: Institución, 2: Tipo de Institución, 3: Nombre del convenio, 4: Fecha Inicio, 5: Fecha Fin, 6: País]
        $datos = [
            ['001-2021', 'BANCO DE COMERCIO', 'Empresa Nacional', 'CONVENIO PARA EL OTORGAMIENTO DE PRÉSTAMOS PERSONALES BAJO LA MODALIDAD DE (DESCUENTO POR PLANILLA) - BANCO DE COMERCIO', '2021-06-01', '2022-06-01', 'Perú'],
            ['002-2021', 'BANCO CONTINENTAL', 'Empresa Nacional', 'CONVENIO PARA EL OTORGAMIENTO DE PRÉSTAMOS PERSONALES BAJO LA MODALIDAD DE DESCUENTO POR PLANILLA – INSTITUCIÓN PÚBLICA (SIN FIANZA) - BANCO CONTINENTAL', '2021-06-15', '2023-06-15', 'Perú'],
            ['003-2021', 'CALIDAD VISUAL SAC', 'Empresa Nacional', 'CONVENIO DE COOPERACIÓN ENTRE CALIDAD VISUAL SAC Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2021-06-18', '2023-06-18', 'Perú'],
            ['004-2021', 'CENTRO DE ESTUDIOS LATINOAMERICANOS DE EDUCACIÓN INCLUSIVA (CELEI)', 'Universidad Internacional', 'CONVENIO MARCO DE COOPERACIÓN ACADÉMICA E INVESTIGACIÓN ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA CORPORACIÓN DE DERECHO PRIVADO SIN FINES DE LUCRO - CENTRO DE ESTUDIOS LATINOAMERICANOS DE EDUCACIÓN INCLUSIVA (CELEI)', '2021-05-03', '2026-05-03', 'Colombia'],
            ['005-2021', 'HOSPITAL DOMINGO OLAVEGOYA DE JAUJA', 'Salud', 'RENOVACION CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE EL HOSPITAL DOMINGO OLAVEGOYA DE JAUJA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ – FACULTAD DE MEDICINA HUMANA', '2021-07-15', '2023-07-15', 'Perú'],
            ['006-2021', 'INSTITUCION EDUCATIVA TECNICA MARÍA INMACULADA - HUANCAYO', 'Institución Educativa', 'CONVENIO ESPECÍFICO ENTRE LA FACULTAD DE TRABAJO SOCIAL DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA INSTITUCION EDUCATIVA TECNICA MARÍA INMACULADA - HUANCAYO', '2021-05-31', '2024-05-31', 'Perú'],
            ['007-2021', 'COMUNIDAD CAMPESINA DE PACA DEL DISTRITO DE PACA PROVINCIA DE JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE PACA DEL DISTRITO DE PACA PROVINCIA DE JAUJA', '2021-08-05', '2026-08-05', 'Perú'],
            ['008-2021', 'COMUNIDAD CAMPESINA DE ULLUSCA DEL DISTRITO DE PARCO PROVINCIA DE JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE ULLUSCA DEL DISTRITO DE PARCO PROVINCIA DE JAUJA', '2021-08-05', '2026-08-05', 'Perú'],
            ['009-2021', 'COMUNIDAD CAMPESINA DEL TINGO DEL DISTRITO DE ACOLLA PROVINCIA DE JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DEL TINGO DEL DISTRITO DE ACOLLA PROVINCIA DE JAUJA', '2021-08-05', '2026-08-05', 'Perú'],
            ['010-2021', 'COMUNIDAD CAMPESINA DE TINGO PACCHA DEL DISTRITO DE PACCHA PROVINCIA DE JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE TINGO PACCHA DEL DISTRITO DE PACCHA PROVINCIA DE JAUJA', '2021-08-05', '2026-08-05', 'Perú'],
            ['011-2021', 'COMUNIDAD CAMPESINA DE POMACANCHA DEL DISTRITO DE POMACANCHA PROVINCIA DE JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE POMACANCHA DEL DISTRITO DE POMACANCHA PROVINCIA DE JAUJA', '2021-08-05', '2026-08-05', 'Perú'],
            ['012-2021', 'COMUNIDAD CAMPESINA DE TRAGADERO DEL DISTRITO DE MARCO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE TRAGADERO DEL DISTRITO DE MARCO', '2021-08-05', '2026-08-05', 'Perú'],
            ['013-2021', 'IE CORY COYLLOR', 'Institución Educativa', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA IE CORY COYLLOR', '2021-08-05', '2026-08-05', 'Perú'],
            ['014-2021', 'UNIVERSIDAD CONTINENTAL SAC Y UNIVERSIDAD NACIONAL MICAELA BASTIDAS DE APURIMAC', 'Universidad Nacional', 'ACUERDO DE ASOCIACIÓN ENTRE LA UNIVERSIDAD CONTINENTAL SAC Y LA UNIVERSIDAD ACIONAL DEL CENTRO DEL PERU - PROYECTO  YACHAY', '2021-04-01', '2023-10-14', 'Perú'],
            ['015-2021', 'INSTITUCION EDUCATIVA POLITÉCNINO TUPAC AMARU', 'Institución Educativa', 'CONVENIO ESPECÍFICO ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ - FACULTAD DE TRABAJO SOCIAL Y LA INSTITUCION EDUCATIVA POLITÉCNINO TUPAC AMARU', '2021-05-31', '2024-05-31', 'Perú'],
            ['016-2021', 'ESCUELA SUPERIOR DE AGRICULTURA LUIZ DE QUEIROZ DE LA UNIVERSIDAD DE SAO PAULO', 'Universidad Internacional', 'CONVENIO ACADÉMICO INTERNACIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA ESCUELA SUPERIOR DE AGRICULTURA LUIZ DE QUEIROZ DE LA UNIVERSIDAD DE SAO PAULO - BRASIL', '2021-07-31', '2026-07-31', 'Brasil'],
            ['017-2021', 'INSTITUTO DE EDUCACION SUPERIOR PEDAGÓGICO PÚBLICO “TEODORO PEÑALOZA” - CHUPACA', 'Otros', 'CONVENIO ESPECIFICO ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ - FACULTAD DE TRABAJO SOCIAL Y EL INSTITUTO DE EDUCACION SUPERIOR PEDAGÓGICO PÚBLICO “TEODORO PEÑALOZA” - CHUPACA', '2021-10-01', '2024-10-01', 'Perú'],
            ['018-2021', 'COMUNIDAD CAMPESINA DE CHONGOS BAJO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE CHONGOS BAJO', '2021-10-20', '2026-10-20', 'Perú'],
            ['019-2021', 'COMUNIDAD CAMPESINA DE AHUAC', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE AHUAC', '2021-10-20', '2026-10-20', 'Perú'],
            ['020-2021', 'COMUNIDAD CAMPESINA DE CHACAPAMPA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE CHACAPAMPA', '2021-10-20', '2026-10-20', 'Perú'],
            ['021-2021', 'COMUNIDAD CAMPESINA DE CHUPURO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE CHUPURO', '2021-10-20', '2026-10-20', 'Perú'],
            ['022-2021', 'COMUNIDAD CAMPESINA DE COLCA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE COLCA', '2021-10-20', '2026-10-20', 'Perú'],
            ['023-2021', 'COMUNIDAD CAMPESINA DEL CENTRO POBLADO DE HUAMANMARCA DISTRITO DE HUAYUCACHI PROVINCIA DE HUANCAYO REGIÓN JUNÍN', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DEL CENTRO POBLADO DE HUAMANMARCA DISTRITO DE HUAYUCACHI PROVINCIA DE HUANCAYO REGIÓN JUNÍN', '2021-07-19', '2024-07-19', 'Perú'],
            ['024-2021', 'COMUNIDAD CAMPESINA DE HUASICANCHA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE HUASICANCHA', '2021-10-20', '2026-10-20', 'Perú'],
            ['025-2021', 'COMUNIDAD CAMPESINA DE HUAYUCACHI', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE HUAYUCACHI', '2021-10-20', '2026-10-20', 'Perú'],
            ['026-2021', 'COMUNIDAD CAMPESINA DE PUCARA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE PUCARA', '2021-10-20', '2026-10-20', 'Perú'],
            ['027-2021', 'COMUNIDAD CAMPESINA DE QUILCAS', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE QUILCAS', '2021-10-20', '2026-10-20', 'Perú'],
            ['028-2021', 'COMUNIDAD CAMPESINA DE SAPALLANGA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE SAPALLANGA', '2021-10-20', '2026-10-20', 'Perú'],
            ['029-2021', 'COMUNIDAD CAMPESINA DE VIQUES', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE VIQUES', '2021-10-20', '2026-10-20', 'Perú'],
            ['030-2021', 'IE. N° 30637 ANDRES AVELINO CACERES DORREGARAY', 'Institución Educativa', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA IE. N° 30637 ANDRES AVELINO CACERES DORREGARAY', '2021-11-05', '2023-11-05', 'Perú'],
            ['031-2021', 'IE EIB ALIPIO PONCE VASQUEZ DE LA COMUNIDAD NATIVA DE TSIRIARI MAZAMARI', 'Institución Educativa', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA IE EIB ALIPIO PONCE VASQUEZ DE LA COMUNIDAD NATIVA DE TSIRIARI MAZAMARI', '2021-11-05', '2023-11-05', 'Perú'],
            ['032-2021', 'IE CEBA SAN MARTIN', 'Institución Educativa', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA IE CEBA SAN MARTIN', '2021-11-05', '2023-11-05', 'Perú'],
            ['033-2021', 'IE JOSÉ CARLOS MARIATEGUI DE MAZAMARI', 'Institución Educativa', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA IE JOSÉ CARLOS MARIATEGUI DE MAZAMARI', '2021-11-05', '2023-11-05', 'Perú'],
            ['034-2021', 'IE RAFAEL HOYOS RUBIO DE MAZAMARI', 'Institución Educativa', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA IE RAFAEL HOYOS RUBIO DE MAZAMARI', '2021-11-05', '2023-11-05', 'Perú'],
            ['035-2021', 'IE SAN MARTIN DE PANGOA', 'Institución Educativa', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA IE SAN MARTIN DE PANGOA', '2021-11-05', '2023-11-05', 'Perú'],
            ['036-2021', 'IE SANTA ROSA DE SANGARENI', 'Institución Educativa', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA IE SANTA ROSA DE SANGARENI', '2021-11-05', '2023-11-05', 'Perú'],
            ['037-2021', 'MUNICIPALIDAD DISTRITAL DE PANGOA', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD DISTRITAL DE PANGOA', '2021-11-04', '2026-11-04', 'Perú'],
            ['038-2021', 'ORGANIZACIÓN DE COMUNIDADES ASHANINKA DEL RIO ENE PANGOA - OCAREP', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA ORGANIZACIÓN DE COMUNIDADES ASHANINKA DEL RIO ENE PANGOA - OCAREP', '2021-11-05', '2023-11-05', 'Perú'],
            ['039-2021', 'ORGANIZACIÓN UNIÓN ASHANINKA NOMATSIGUENGA DEL VALLE DE PANGOA - KANUJA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA ORGANIZACIÓN UNIÓN ASHANINKA NOMATSIGUENGA DEL VALLE DE PANGOA - KANUJA', '2021-11-05', '2023-11-05', 'Perú'],
            ['040-2021', 'UNIVERSIDAD CATÓLICA DEL PERÚ', 'Universidad Privada', 'CONVENIO DE ASOCIACIÓN ENTRE LA UNIVERSIDAD CATÓLICA DEL PERÚ, UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA UNIVERSIDAD NACIONAL MICAELA BASTIDAS DE APURIMAC', '2021-08-03', '2022-08-03', 'Perú'],
            ['041-2021', 'INSTITUTO REGIONAL DE ENFERMEDADES NEOPLÁSICAS DEL CENTRO - IREN', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTRE ASISTENCIAL ENTRE EL INSTITUTO REGIONAL DE ENFERMEDADES NEOPLÁSICAS DEL CENTRO - IREN  Y UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ - FACULTAD DE MEDICINA HUMANA -UNIDAD DE POSGRADO DE MEDICINA', '2021-01-01', '2021-12-31', 'Perú'],
            ['042-2021', 'CENTRO DE EDUCACIÓN TÉCNICO PRODUCTIVA - CHUPACA', 'Institución Educativa', 'CONVENIO ESPECIFICO ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ - FACULTAD DE TRABAJO SOCIAL Y EL CENTRO DE EDUCACIÓN TÉCNICO PRODUCTIVA - CHUPACA', '2021-09-30', '2024-09-30', 'Perú'],
            ['043-2021', 'COMIETE DE ADMINISTRACIÓN DE LOS RECURSOS PARA CAPACITACIÓN CAREC', 'Otros', 'RENOVACIÓN DE CONVENIO MARCO DE COOPERACIÓN CELEBRADO ENTRE EL COMIETE DE ADMINISTRACIÓN DE LOS RECURSOS PARA CAPACITACIÓN CAREC Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL LPERÚ', '2021-10-25', '2024-10-25', 'Perú'],
            ['044-2021', 'COMANDO DE SALUD DEL EJÉRCITO DEL PERÚ (COSALE)', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTE ASISTENCIAL, INVESTIGACIÓN CIENTÍFICA Y DE BIENESTAR ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ - FACULTAD DE MEDICINA HUMANA (HUANCAYO) Y EL COMANDO DE SALUD DEL EJÉRCITO DEL PERÚ (COSALE)', '2021-12-28', '2023-12-28', 'Perú'],
            ['045-2021', 'UNIVERSIDAD NACIONAL INTERCULTURAL DE LA SELVA CENTRAL JUAN SANTOS ATAHUALPA', 'Universidad Nacional', 'CONVENIO DE COOPERACIÓN INTERINSTUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA UNIVERSIDAD NACIONAL INTERCULTURAL DE LA SELVA CENTRAL JUAN SANTOS ATAHUALPA', '2021-12-17', '2026-12-17', 'Perú'],
            ['046-2021', 'RED DE SALUD VALLE DEL MANTARO', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE LA RED DE SALUD VALLE DEL MANTARO Y LA FACULTAD DE MEDICINA HUMANA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2021-10-14', '2022-10-14', 'Perú'],
            ['047-2021', 'COMUNIDAD CAMPESINA DE CHOCON DEL DISTRITO DE ACOLLA PROVINCIA DE JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE CHOCON DEL DISTRITO DE ACOLLA PROVINCIA DE JAUJA', '2021-08-05', '2023-08-05', 'Perú'],
            ['048-2021', 'COMUNIDAD CAMPESINA DE HUALHUAS', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE HUALHUAS', '2021-12-23', '2023-12-23', 'Perú'],
            ['049-2021', 'COMUNIDAD CAMPESINA DE MARCAPOMACOCHA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE MARCAPOMACOCHA', '2021-12-10', '2023-12-10', 'Perú'],
            ['050-2021', 'I.E. SAN RAMON', 'Institución Educativa', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA I.E. SAN RAMON', '2021-11-05', '2023-11-05', 'Perú'],
            ['051-2021', 'COMUNIDAD CAMPESINA DE LA BREÑA DISTRITO DE HUACRAPUQUIO PROVINCIA DE HUANCAYO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE LA BREÑA DISTRITO DE HUACRAPUQUIO PROVINCIA DE HUANCAYO', '2021-10-20', '2026-10-20', 'Perú'],
            ['052-2021', 'COMUNIDAD CAMPESINA DE LLOCLLAPAMPA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE LLOCLLAPAMPA', '2021-08-05', '2023-08-05', 'Perú'],
            ['053-2021', 'COMUNIDAD CAMPESINA DE SANTA ROSA DE SACCO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE SANTA ROSA DE SACCO', '2021-11-04', '2026-11-04', 'Perú'],
            ['054-2021', 'COMUNIDAD CAMPESINA DE SAN FRANCISCO DE ASIS DE YANTAC', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE SAN FRANCISCO DE ASIS DE YANTAC', '2021-11-05', '2026-11-05', 'Perú'],
            ['055-2021', 'COMUNIDAD CAMPESINA DE SUITUCANCHA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE SUITUCANCHA', '2021-11-05', '2021-11-05', 'Perú'],
            ['056-2021', 'COMUNIDAD CAMPESINA DE SAN JERÓNIMO DE LA OROYA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE SAN JERÓNIMO DE LA OROYA', '2021-12-10', '2026-12-10', 'Perú'],
            ['057-2021', 'COMUNIDAD CAMPESINA DE PACHACHACA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE PACHACHACA', '2021-11-05', '2026-11-05', 'Perú'],
            ['058-2021', 'COMUNIDAD CAMPESINA DE HUAYPACHA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE HUAYPACHA', '2021-11-06', '2026-11-06', 'Perú'],
            ['059-2021', 'COMUNIDAD CAMPESINA DE CARHUACAYAN', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE CARHUACAYAN', '2021-11-10', '2026-11-10', 'Perú'],
            ['060-2021', 'COMUNIDAD CAMPESINA DE PURISIMA CONCEPCIÓN PACCHA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE PURISIMA CONCEPCIÓN PACCHA', '2021-11-08', '2026-11-08', 'Perú'],
            ['061-2021', 'COMUNIDAD CAMPESINA DE CHUQUIQUIRPAY', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE CHUQUIQUIRPAY', '2021-11-09', '2026-11-09', 'Perú'],
            ['062-2021', 'COMUNIDAD CAMPESINA DE HUAYNACANCHA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE HUAYNACANCHA', '2021-11-10', '2026-11-10', 'Perú'],
            ['063-2021', 'COMUNIDAD CAMPESINA DE HUAYHUAY', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE HUAYHUAY', '2021-11-11', '2023-11-11', 'Perú'],
            ['064-2021', 'COMUNIDAD CAMPESINA DE CHACAPALPA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE CHACAPALPA', '2021-08-05', '2026-08-05', 'Perú'],
            ['065-2021', 'COMUNIDAD CAMPESINA DE HUARIPAMPA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE HUARIPAMPA', '2021-08-05', '2026-08-05', 'Perú'],
            ['066-2021', 'COMUNIDAD CAMPESINA DE MARCO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE MARCO', '2021-08-05', '2026-08-05', 'Perú'],
            ['067-2021', 'COMUNIDAD CAMPESINA DE NUEVA ESPERANZA DE APATA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE NUEVA ESPERANZA DE APATA', '2021-08-05', '2026-08-05', 'Perú'],
            ['068-2021', 'COMUNIDAD CAMPESINA DE 3ER CUARTEL-ACOLLA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE 3ER CUARTEL-ACOLLA', '2021-08-05', '2026-08-05', 'Perú'],
            ['069-2021', 'COMUNIDAD CAMPESINA DE 2DO CUARTEL ACOLLA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE 2DO CUARTEL ACOLLA', '2021-08-05', '2026-08-05', 'Perú'],
            ['070-2021', 'COMUNIDAD CAMPESINA DE SALLAHUACHAC DEL DISTRITO DE SINCOS PROVINCIA DE JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE SALLAHUACHAC DEL DISTRITO DE SINCOS PROVINCIA DE JAUJA', '2021-08-05', '2026-08-05', 'Perú'],
            ['071-2021', 'COMUNIDAD CAMPESINA DE ARAMACHAY', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE ARAMACHAY', '2021-08-05', '2026-08-05', 'Perú'],
            ['072-2021', 'COMUNIDAD CAMPESINA DE MOLINOS DEL DISTRITO DE MOLINOS PROVINCIA DE JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE MOLINOS DEL DISTRITO DE MOLINOS PROVINCIA DE JAUJA', '2021-08-05', '2026-08-05', 'Perú'],
            ['073-2021', 'COMUNIDAD CAMPESINA DE HUERTAS DEL DISTRITO DE HUERTAS PROVINCIA DE JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE HUERTAS DEL DISTRITO DE HUERTAS PROVINCIA DE JAUJA', '2021-08-05', '2026-08-05', 'Perú'],
            ['074-2021', 'UNIVERSIDAD DE ESTUDIOS INTERNACIONALES DE HEBEI', 'Universidad Internacional', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD DE ESTUDIOS INTERNACIONALES DE HEBEI Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2021-09-02', '2026-09-02', 'China'],
            ['075-2021', 'FUNDACIÓN PARA EL DESARROLLO DEL CENTRO DEL PERÚ - FUDEC', 'Otros', 'CCONVENIO ESPECÍFICO DE DONACIÓN CONDICIONADA DE TRUCHAS REPRODUCTORAS DEL SUBPROYECTO N° PNIPA-ACU-SIADE-PP-000081- DEL CENTRO DE INVESTIGACIÓN EN BIOTECNOLOGÍA DE ALIMENTOS FUNCIONALES CONFORMADO POR LOS INVESTIGADORES DE LA FACULTAD DE ZOOTECNIA, FACULTAD DE ING. INDUSTRIAS ALIMENTARIAS Y LA FUNDACIÓN PARA EL DESARROLLO DEL CENTRO DEL PERÚ', '2021-08-04', '2023-08-04', 'Perú'],
            ['076-2021', 'FUNDACIÓN PARA EL DESARROLLO DEL CENTRO DEL PERÚ - FUDEC', 'Otros', 'ADENDA AL CONVENIO ESPECÍFICO DE COOPERACIÓN ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA FUNDACIÓN PARA EL DESARROLLO DEL CENTRO DEL PERÚ - FUDEC SOBRE EL CENTRO EXPERIMENTAL Y PRODUCCIÓN CASARACRA - UNCP', '2021-10-21', '2025-10-21', 'Perú'],
            ['077-2021', 'INSTITUTO REGIONAL DE ENFERMEDADES NEOPLÁSICAS DEL CENTRO - IREN', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTRE ASISTENCIAL ENRE EL INSTITUTO REGIONAL DE ENFERMEDADES NEOPLÁSICAS DEL CENTRO Y LA FACULTAD DE ENFERMERÍA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2021-10-21', '2025-10-21', 'Perú'],
            ['078-2021', 'RED DE SALUD DE SATIPO', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE LA RED DE SALUD DE SATIPO Y LA FACULTAD DE ENFERMERÍA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2021-11-21', '2023-11-21', 'Perú'],
            ['079-2021', 'MINISTERIO DE EDUCACION', 'Otros', 'CONVENIO DE COLABORACION INTERINSTITUCIONAL ENTRE EL MINISTERIO DE EDUCACION Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2021-04-13', '2021-12-31', 'Perú'],
            ['080-2021', 'CAJA HUANCAYO', 'Empresa Nacional', 'CONVENIO INTERINSTITUCIONAL PARA PRESTACION DE SERVICIO DE COBRANZA Y OTROS ENTRE LA CAJA HUANCAYO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2021-04-05', '2022-04-05', 'Perú'],
            ['081-2021', 'CENTRO INTERNACIONAL DE LA PAPA - CIP', 'Otros', 'CONVENIO DE COLABORACION ENTRE EL CENTRO INTERNACIONAL DE LA PAPA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2021-08-25', '2022-02-25', 'Perú'],
            ['082-2021', 'UNIDAD EJECUTORA N°118 MEJORAMIENTO DE LA CALIDAD DE EDUCACIÓN BASÍCA Y SUPERIOR', 'Otros', 'CONVENIO DE COOPERACIÓN INSTITUCIONAL ENTRE LA UNIDAD EJECUTORA N°118 MEJORAMIENTO DE LA CALIDAD DE EDUCACIÓN BASÍCA Y SUPERIOR Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2021-08-10', '2022-08-10', 'Perú'],
            ['083-2021', 'INSTITUTO TECNOLÓGICO DE LA PRODUCCIÓN - ITP', 'Otros', 'CONVENIO DE COOPERACIÓN ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL INSTITUTO TECNOLÓGICO DE LA PRODUCCIÓN', '2021-08-31', '2024-08-31', 'Perú'],
            ['084-2021', 'PROGRAMA NACIONAL DE INNOVACIÓN EN PESCA Y ACUICULTURA', 'Otros', 'CONTRATO DE ADJUDICACION DE RECURSOS  REEMBOLSABLES DEL PROGRAMA NACIONAL DE INNOVACIÓN EN PESCA Y ACUICULTURA', '2021-09-18', '2022-09-18', 'Perú'],
            ['085-2021', 'CLINICA DENTAL PREMIUM EIRL', 'Empresa Nacional', 'CONVENIO INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA CLINICA DENTAL PREMIUM EIRL', '2021-09-01', '2023-09-01', 'Perú'],
            ['086-2021', 'PROVIAS NACIONAL - MTC', 'Otros', 'CONVENIO DE PRÁCTICAS PREPROFECIONALES N° 023-2021-MTC/20.5-PRE', '2021-12-30', '2022-03-31', 'Perú'],
        ];

        foreach ($datos as $fila) {
            
            $nombreInstitucion = strtoupper($fila[1]);
            $tipoInstitucion = $fila[2];
            $pais = $fila[6];


            // Buscar o crear la institución
            $institucion = Institution::firstOrCreate(
                ['name' => $nombreInstitucion],
                ['country' => $pais, 'type' => $tipoInstitucion]
            );

            // Asignar el ID del tipo de convenio
            $nombreLargo = strtoupper($fila[3]);
            
            if (str_contains($nombreLargo, 'MEMORANDO')) {
                $tipoId = $tipos['memorando']->id;
            } elseif (str_contains($nombreLargo, 'ESPECIFICO') || str_contains($nombreLargo, 'ESPECÍFICO') || str_contains($nombreLargo, 'ADENDA') || str_contains($nombreLargo, 'CONTRATO')) {
                $tipoId = $tipos['especifico']->id; 
            } else {
                $tipoId = $tipos['marco']->id;
            }

            // 1. Creamos el convenio y lo guardamos en una variable
            $agreement = Agreement::create([
                'title' => $fila[0],
                'name' => $fila[3],
                'resolution_number' => $fila[0],
                'institution_id' => $institucion->id,
                'agreement_type_id' => $tipoId, 
                'start_date' => $fila[4],
                'end_date' => $fila[5],
                'status' => 'Vigente'
            ]);

            // 2. Lógica actualizada para buscar en subcarpetas por año
            $codigo = $fila[0]; // Ej: '001-2024'
            
            // Extraemos los últimos 4 caracteres del código para obtener el año (ej: '2024')
            $anio = substr($codigo, -4); 
            
            // Armamos la ruta incluyendo la carpeta del año
            $rutaRelativa = "convenios/{$anio}/{$codigo}.pdf"; 

            // Verificamos si existe y lo guardamos
            if (\Illuminate\Support\Facades\Storage::disk('public')->exists($rutaRelativa)) {
                $agreement->documents()->create([
                    'name' => 'Doc - ' . ($agreement->resolution_number ?? $agreement->title),
                    'file_path' => $rutaRelativa,
                    'extension' => 'pdf'
                ]);
            }
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}