<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Agreement;
use App\Models\Institution;
use App\Models\AgreementType;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class Convenios2018Seeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        $tipos = [
            'marco' => AgreementType::firstOrCreate(['name' => 'Convenio Marco']),
            'especifico' => AgreementType::firstOrCreate(['name' => 'Convenio Específico']),
            'memorando' => AgreementType::firstOrCreate(['name' => 'Memorando de Entendimiento']),
            'adenda' => AgreementType::firstOrCreate(['name' => 'Adenda']),
        ];
        
        $datos = [
            ['001-2018', 'IMPULSA PERÚ', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL N°001 - 2017 SUSCRITO ENTRE EL PROGRAMA NACIONAL PARA LA PROMOCIÓN DE OPORTUNIDADES LABORALES "IMPULSA PERÚ" DEL MINISTERIO DE TRABAJO Y PROMOCIÓN D...', null, '2018-12-06', 'Perú'],
            ['002-2018', 'CLÍNICA CAYETANO HEREDIA', 'Otros', 'CONVENIO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE LA FACULTAD DE MEDICINAHUMANA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ" Y LA CLÍNICA CAYETANO HEREDIA', null, null, 'Perú'],
            ['003-2018', 'CONTASIS S.A.C.', 'Empresa Nacional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y CONTASIS S.A.C', '2017-07-13', '2022-07-13', 'Perú'],
            ['004 - 2018', 'LA FUNDACIÓN UNIVERSITARIA MONSERRATE UNIMONSERRATE', 'Otros', 'LA FUNDACIÓN UNIVERSITARIA MONSERRATE UNIMONSERRATE', null, '2020-11-09', 'Perú'],
            ['005-2018', 'AGENCIA AGRARIA DE CHUPACA', 'Otros', 'CARTA DE INTENCIÓN DE COOPERACIÓN ITERINSTITUCIONAL ENTRE LA FACULTAD DE ZOOTECNIA DE LA UNIVERSIDAD ANCIONAL DEL CENTRO DEL PERÚ Y LA AGANCIA AGRARIA DE CHUPACA - -REGIÓN JUNÍN', '2017-12-04', null, 'Perú'],
            ['006-2018', 'CÁMARA DE COMERCIO DE  HUANCAYO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA CÁMARA DE COMERCIO DE HUANCAYO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-04-02', '2020-04-02', 'Perú'],
            ['007-2018', 'INDECOPI', 'Otros', 'CONVENIO DE COLABORACIÓN PARA EL ESTABLECIMIENTO DE UN CENTRO DE APOYO A LA TECNOLOGIA Y LA INNOVACIÓN (CATI) EN LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ COMO INSTITUCIÓN INTEGRANTE DE LA RED NA...', '2018-04-06', '2020-04-06', 'Perú'],
            ['008-2018', 'UNIVERSIDAD PRIVADA DE HUANCAYO FRANKILN ROSEVELT', 'Educación', 'CONVENIO MARCO ENTRE LA UNIVERSIDAD PRIVADA DE HUANCAYO FRANKLIN ROSEVELT Y LA UNIVERISDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-04-09', '2023-04-09', 'Perú'],
            ['009-2018', 'EMPRESA ESTRATEGIAS DIGITALES', 'Empresa Nacional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA EMPRESA ESTRATEGIAS  DIGITALES.', null, '2020-04-13', 'Perú'],
            ['010-2018', 'INGEMMET', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE EL INSTITUTO GEOLÓGICO, MINERO Y METALÚRGICO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-04-20', '2023-04-20', 'Perú'],
            ['011-2018', 'PRONABEC', 'Otros', 'CONVENIO ESPECIFICO DE COOPERACIÓN INTERINSTITUCIONAL PARA LA IMPLEMENTACIÓN DE LA "BECA PERMANENCIA DE ESTUDIOS-NACIONAL" ENTRE EL PROGRAMA NACIONAL DE BECAS Y CREDITO EDUCATIVO (PRONABEC) Y LA UN...', '2018-04-27', '2023-04-27', 'Perú'],
            ['012-2018', 'RED DE SALUD DE JUNIN', 'Salud', 'CONVENIO ESPECIFICO PARA PRESTACION DE SERVICIOS DE SALUD - RED DE SALUD JUNIN - UNCP', '2018-05-18', '2020-05-18', 'Perú'],
            ['013-2018', 'RED DE SALUD DE JAUJA', 'Salud', 'CONVENIO ESPECIFICO PARA PRESTACION DE SERVICIOS DE SALUD - RED DE SALUD JAUJA - UNCP', '2018-05-18', '2020-05-18', 'Perú'],
            ['014-2018', 'RED DE SALUD DE TARMA', 'Salud', 'CONVENIO ESPECIFICO PARA PRESTACION DE SERVICIOS DE SALUD - RED DE SALUD TARMA - UNCP', '2018-05-18', '2020-05-18', 'Perú'],
            ['015-2018', 'RED DE SALUD DE SATIPO', 'Salud', 'CONVENIO ESPECIFICO PARA PRESTACION DE SERVICIOS DE SALUD - RED DE SALUD SATIPO - UNCP', '2018-05-18', '2020-05-18', 'Perú'],
            ['016-2018', 'MUNICIPALIDAD DISTRITAL DE ANDAMARCA CONCEPCIÓN', 'Sector Público', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD DISTRITAL DE ANDAMARCA CONCEPCION Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-04-05', '2022-04-05', 'Perú'],
            ['017-2018', 'ELECTROCENTRO S.A.', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y ELECTROCENTRO S.A.', '2018-05-17', null, 'Perú'],
            ['018-2018', 'IESTP SAN MARTIN DE PANGOA', 'Educación', 'CONVENIO ESPECIFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL IESTP SAN MARTIN DE PANGOA', '2018-06-17', '2019-06-17', 'Perú'],
            ['019-2018', 'UNIVERSITAT POLITECNICA DE CATALUNYA - UPC BARCELONA ESPAÑA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN ACADEMICA ENTRE LA UNIVERSITAT POLITECNICA DE CATALUNYA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-01-30', '2022-01-30', 'Perú'],
            ['020-2018', 'UNIVERSITAT POLITECNICA DE CATALUNYA - UPC BARCELONA ESPAÑA', 'Otros', 'CONVENIO ESPECIFICO DE INTERCAMBIO DE PERSONAL DOCENTE E INVESTIGADORES ENTRE LA ESCUELA SUPERIOR DE INGENIEREIAS INDUSTRIAL, AEROSPACIAL Y AUDIVISUAL DE LA UNIVERSITAT POLITECNICA DE CATALUNYA Y L...', '2018-01-30', '2022-01-30', 'Perú'],
            ['021-2018', 'INSUMEX S.A.', 'Otros', 'CONVENIO ESPECÍFICO DE CONCESIÓN PLANTA CONCENTRADORA DE MINERALES HUARI DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA INSUMEX S.A.', '2018-05-16', '2020-05-16', 'Perú'],
            ['022-2018', 'MUNICIPALIDAD DISTRITAL DE RIO NEGRO', 'Sector Público', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD DISTRITAL DE RIO NEGRO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-06-01', '2019-06-01', 'Perú'],
            ['023-2018', 'UNIVERSIDAD DE FEDERAL DO CEARÁ (BRASIL)', 'Educación', 'CONVENIO DE COLABORACIÓN ENTRE LA UNIVERSIDAD DE FEDERAL DO CEARÁ (BRASIL) Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-06-07', '2023-06-07', 'Perú'],
            ['024-2018', 'SOUTH DAKOTA SCHOOL OF MINES & TECNOLOGY RAPID CITY, SOUTH DAKOTA, USA', 'Otros', 'MEMORANDUM OF UNDERTANDING BETWEEN SOUTH DAKOTA SCHOOL OF MINES & TECNOLOGY RAPID CITY, SOUTH DAKOTA, USA AND UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-05-29', '2023-05-29', 'Perú'],
            ['025-2018', 'CAMARA DE COMERCIO E INDUSTRIAS SATIPO', 'Otros', 'CONVENIO ESPECIFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA CAMARA DE COMERCIO E INDUSTRIAS SATIPO', '2018-06-15', '2019-06-15', 'Perú'],
            ['026-2018', 'EREBOR SRL.', 'Empresa Nacional', 'CONVENIO ESPECÍFICO DE CONCESIÓN PLANTA CONCENTRADORA DE MINERALES HUARI DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA EMPRESA EREBOR COMPAÑÍA MINERA S.R.L.', '2018-06-08', '2020-06-08', 'Perú'],
            ['027-2018', 'MARMOLES SCRLtda.', 'Otros', 'CONVENIO DE COOPERACIÓN TECNICA INTERINSTITUCIONAL ENTRE LA UNCP Y LA COMPAÑÍA MINERA MARMOLES SCRLtda.', '2018-07-09', '2020-07-09', 'Perú'],
            ['028-2018', 'COOPERATIVA ACUACOOPS', 'Otros', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE COOPERATIVA DE SERVICIOS MÚLTIPLES ACUÍCOLA VRAEM SATIPO “ACUACOOPS” Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-06-18', '2020-06-18', 'Perú'],
            ['029-2018', 'CORE FOUNDATION', 'Otros', 'MEMORANDO DE ENTENDIMIENTO ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y CORE FOUNDATION DE INDIANA ESTADOS UNIDOS', '2018-05-08', '2023-05-08', 'Perú'],
            ['030-2018', 'MUNICIPALIDAD DISTRITAL DE MAZAMARI', 'Sector Público', 'CONVENIO ESPECIFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNCP Y LA MUNICIPALIDAD DISTRITAL DE MAZAMARI', '2018-06-04', '2019-06-04', 'Perú'],
            ['031-2018', 'UNIVERSIDAD CENTRAL DE ECUADOR', 'Educación', 'CONVENIO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD CENTRAL DE ECUADOR Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-07-18', '2023-07-18', 'Perú'],
            ['032-2018', 'UNIVERSIDAD DE RIO DE JANEIRO', 'Educación', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD FEDERAL RURAL DE RIO DE JANEIRO (UFRRJ) Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-06-19', '2023-06-19', 'Perú'],
            ['033-2018', 'CONIDA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNCP Y LA COMISIÓN NACIONAL DE INVESTIGACIÓN  DESARROLLO AEROESPACIAL - CONIDA', '2018-06-29', '2020-06-29', 'Perú'],
            ['034-2018', 'IESTP PUERTO LIBRE', 'Educación', 'CONVENIO DE COOPERACIÓN ENTRE LA UNCP Y EL INSTITUTO DE EDUCACIÓN SUPERIOR TECNOLOGICO PUERTO LIBRE - PERENE CHANCHAMAYO', '2018-06-28', '2021-06-28', 'Perú'],
            ['035-2018', 'COMUNIDAD CAMPESINA DE ANDAMARCA CONCEPCION', 'Comunidades', 'RENOVACIÓN DE CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNCP Y LA COMUNIDAD CAMPESINA DE PUCACOCHA ANDAMARCA PROVINCIA DE CONCEPCIÓN', '2018-08-14', '2020-08-14', 'Perú'],
            ['036-2018', 'DIRECCION REGIONAL DE ENERGIA Y MINAS', 'Sector Público', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL GOBIERNO REGIONAL JUNÍN', '2018-08-29', null, 'Perú'],
            ['037-2018', 'DIRECTOR DEL IESTP SAM', 'Educación', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL INSTITUTO DE EDUCACIÓN SUPERIOR TECNOLOGICO PUBLICO SANTIAGO ANTUNEZ DE MAYOLO', '2018-08-14', '2021-08-14', 'Perú'],
            ['038-2018', 'UNCP', 'Otros', 'CONVENIO ESPECÍFICO DE PRÁCTICAS PRE PROFESIONALES ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA FACULTAD DE CIENCIAS DE LA COMUNICACIÓN', null, null, 'Perú'],
            ['039-2018', 'RIKOLTO', 'Otros', 'CARTA DE INTENCIÓN PARA LA COOPERACIÓN ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y RIKOLTO: ORGANIZACIÓN DE RED INTERNACIONAL', '2018-07-23', '2022-07-23', 'Internacional'],
            ['040-2018', 'COLEGIO SALESIANO DON BOSCO', 'Educación', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ - FACULTAD DE TRABAJO SOCIAL Y LA INSTITUCIÓN EDUCATIVA SALESIANO DON BOSCO DE HUANCAYO', '2018-06-28', '2021-06-28', 'Perú'],
            ['041-2018', 'ERET SAC', 'Empresa Nacional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y ENVIROANDES-REMEDIATION ENVIRONMENTAL TECHNOLOGIES SAC (ERET)', '2018-08-16', '2023-08-16', 'Perú'],
            ['042-2018', 'ASOCIACION EN PARTICIPACION', 'Otros', 'CONVENIO DE ASOCIACIÓN EN PARTICIPACIÓN PARA EJECUTAR EL PROYECTO DE INVESTIGACIÓN TITULADO "RESTAURACIÓN DE ECOSISTEMAS DE REGULACIÓN HÍDRICA MEDIANTE REFORESTACIÓN CON TRES ESTRATOS Y SISTEMAS DE...', null, null, 'Perú'],
            ['043-2018', 'INIA', 'Otros', 'ACTA DE ENTENDIMIENTO N° 006-2018 ENTRE LA ESTACIÓN EXPERIMENTAL AGRARIA SANTA ANA - JUNIN INIA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-09-03', '2023-09-03', 'Perú'],
            ['044-2018', 'HEALTH CREEH', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL CENTER FOR RESEARCH ENVIRONMENTAL HEALTH - CREEH', '2018-09-12', '2023-09-12', 'Perú'],
            ['045-2018', 'HOSPITAL REBAGLIATI', 'Salud', 'CONVENIO ESPECÍFICO ENTRE EL HOSPITAL NACIONAL EDGARDO REBAGLIATI MARTINS Y LA FACULTAD DE MEDICINA HUMANA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-07-12', null, 'Perú'],
            ['046-2018', 'PROGRAMA NACIONAL DE INNOVACIÓN EN PESCA Y ACUICULTURA', 'Sector Público', 'CONVENIO DE ASOCIACIÓN EN PARTICIPACIÓN PARA EJECUTAR EL PROYECTO DE INVESTIGACIÓN TITULADO "ASISTENCIA TECNICA EN BUENAS PRACTICAS ACUICOLAS PARA LA CRIANZA DE GAMITANA Y PACO EN LOS SOCIOS DE LA ...', null, null, 'Perú'],
            ['047-2018', 'COMUNIDAD DE LLOCLLAPAMPA', 'Comunidades', 'CONVENIO DE COOPERACIÓN TÉCNICA INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD DE LLOCLLAPAMPA', '2018-06-28', '2020-06-28', 'Perú'],
            ['048-2018', 'PROGRAMA NACIONAL DE INNOVACIÓN EN PESCA Y ACUICULTURA', 'Sector Público', 'CONVENIO DE ASOCIACIÓN EN PARTICIPACIÓN PARA EJECUTAR EL PROYECTO DE INVESTIGACIÓN TITULADO "MEJORAMIENTO DE CAPACIDADES MEDIANTE TRANSFERENCIA TECNOLÓGICA PARA PROCESO PRODUCTIVO Y COMERCIALIZACIÓ...', null, null, 'Perú'],
            ['049-2018', 'CONSULTING GROUP SAC', 'Empresa Nacional', 'CONVENIO MARCO PARA ALIANZA ESTRATÉGICA ENTRE LA EMPRESA AGUIRRE CONSULTING GROUP SAC Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-09-24', '2021-09-24', 'Perú'],
            ['050-2018', 'UAM', 'Otros', 'CONVENIO ESPECÍFICO DE COOPERACIÓN PARA EL INTERCAMBIO ACADÉMICO ENTRE LA UNIVERSIDAD AUTÓNOMA METROPOLITANA DE LOS ESTADOS UNIDOS MEXICANOS Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-06-28', '2022-06-28', 'Perú'],
            ['051-2018', 'COOPERATIVA AGRARIA CAFETALERA PANGOA LTDA.', 'Otros', 'CONVENIO INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COOPERATIVA AGRARIA CAFETALERA PANGOA LTDA.', '2018-06-22', '2021-06-22', 'Perú'],
            ['052-2018', 'UNSM-T', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DE SAN MARTÍN - TARAPOTO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-09-10', '2023-09-10', 'Perú'],
            ['053-2018', 'AQUA SAN PEDRO S.A.C.', 'Empresa Nacional', 'CONVENIO DE ASOCIACIÓN EN PARTICIPACIÓN', '2018-08-16', null, 'Perú'],
            ['054-2018', 'DIRECCIÓN REGIONAL DE AGRICULTURA JUNÍN', 'Sector Público', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA DIRECCIÓN REGIONAL DE AGRICULTURA JUNÍN', '2018-10-24', '2023-10-24', 'Perú'],
            ['055-2018', 'ESTABLECIMIENTOS DE SALUD', 'Salud', 'CONVENIO MARCO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE EL MINISTERIO DE SALUD, EL GOBIERNO REGIONAL JUNÍN Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', null, null, 'Perú'],
            ['056-2018', 'CAJA CENTRO', 'Otros', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL PARA EL OTORGAMIENTO DE PRESTAMOS PERSONALES CON DESCUENTO POR PLANILLA DE REMUNERACIONES', null, null, 'Perú'],
            ['057-2018', 'RENIEC', 'Otros', 'CONVENIO DE VERIFICACIÓN BIOMÉTRICA DE LA IDENTIDAD DE LAS PERSONAS ENTRE EL REGISTRO NACIONAL DE IDENTIFICACIÓN Y ESTADO CIVIL Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-11-05', null, 'Perú'],
            ['058-2018', 'UNIVERSIDAD NACIONAL DE INGENIERÍA', 'Universidad Nacional', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONALDE INGENIERÍA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-10-26', '2022-10-26', 'Perú'],
            ['059-2018', 'IGSAC', 'Empresa Nacional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA EMPRESA INNOVACIÓN EN GESTIÓN S.A.C.', '2018-11-22', '2021-11-22', 'Perú'],
            ['060-2018', 'CAP - RJ', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL COLEGIO DE ARQUITECTOS DEL PERÚ - REGIONAL JUNÍN', '2018-11-22', '2021-11-22', 'Perú'],
            ['061-2018', 'ONG ASOCIACIÓN PROTECCIÓN AMBIENTAL Y DESARROLLO SOSTENIBLE - PADES.', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA ONG ASOCIACIÓN PROTECCIÓN AMBIENTAL Y DESARROLLO SOSTENIBLE - PADES Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-11-30', '2021-11-30', 'Perú'],
            ['062-2018', 'MUNICIPALIDAD PROVINCIAL DE SATIPO', 'Sector Público', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD PROVINCIAL DE SATIPO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-12-17', '2023-12-17', 'Perú'],
            ['063-2018', 'MUNICIPALIDAD PROVINCIAL DE SATIPO 

RED DE SALUD SATIPO', 'Sector Público', 'CONVENIO TRIPARTITO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PER[U, LA RED DE SALUD SATIPO Y LA MUNICIPALIDAD PROVINCIAL DE SATIPO', '2018-12-17', '2020-12-17', 'Perú'],
            ['064-2018', 'CENTRO DE INVESTIGACIÓN EN ALTA MONTAÑA', 'Otros', 'ACTA DE ENTENDIMIENTO ENTRE LA RED DE INVESTIGACÓN EN ECOSISTEMAS DE MONTAÑA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PER[U', '2018-12-10', '2023-12-10', 'Perú'],
            ['065-2018', 'COMANDO DE SALUD DEL EJERCITO (COSALE)', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTE ASISTENCIAL, INVESTIGACIÓN Y SERVICIOS ENTRE EL COMANDO DE SALUD DEL EJÉRCITO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ / FACULTAD DE MEDICINA HUMANA', '2018-12-31', '2019-12-31', 'Perú'],
            ['066-2018', 'COMUNIDAD CAMPESINA SAN AGUSTIN', 'Comunidades', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA SAN AGUSTIN', '2018-12-21', '2020-12-21', 'Perú'],
            ['067-2018', 'MINISTERIO DE LA PRODUCCIÓN', 'Sector Público', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE EL MINISTERIO DE LA PRODUCCIÓN Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-11-23', '2019-11-23', 'Perú'],
            ['068-2018', 'CORPORACIÓN EDUCATIVA SAN JUAN BOSCO', 'Otros', 'CONVENIO INTERINSTITUCIONAL ENTRE LA CORPORACIÓN EDUCATIVA SAN JUAN BOSCO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2018-12-21', '2019-12-31', 'Perú'],
            ['069-2018', 'FACULTAD DE MINAS', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y CENTRO DE INVESTIGACIÓNY ESTUDIOS MEDIO AMBIENTAKES S.A.C. - CIEMAM S.A.C.', null, null, 'Perú'],
            ['070-2018', 'PERDUE UNIVERSITY', 'Otros', 'MEMORANDUM OF UNDERSTANDING BETWEEN PERDUE UNIVERSITY WEST LAFAYETTE, INDIANA, USA AND NATIONAL UNIVERSITY OF THE CENTER OF PERU, JUNIN, HUANCAYO, PERU', '2018-12-09', '2023-12-09', 'Perú'],
            ['071-2018', 'THE CENTRE FOR EXCELLENCE IN MINING INNOVATION', 'Otros', 'MEMORANDUM OS UNDERSTANDING BETWEEN THE UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ (UNCP) AND THE CENTRE FOR EXCELLENCE IN MINING INNOVATION', '2018-05-31', '2023-05-31', 'Perú'],
        ];

        foreach ($datos as $fila) {
            $nombreInstitucion = strtoupper($fila[1]);
            $tipoEstandarizado = $fila[2];
            $pais = $fila[6];

            $institucion = Institution::firstOrCreate(
                ['name' => $nombreInstitucion],
                ['country' => $pais, 'type' => $tipoEstandarizado]
            );

            $nombreLargo = strtoupper($fila[3]);
            
            if (str_contains($nombreLargo, 'MEMORANDO')) {
                $tipoId = $tipos['memorando']->id;
            } elseif (str_contains($nombreLargo, 'ADENDA')) {
                $tipoId = $tipos['adenda']->id;
            } elseif (str_contains($nombreLargo, 'ESPECIFICO') || str_contains($nombreLargo, 'ESPECÍFICO')) {
                $tipoId = $tipos['especifico']->id;
            } else {
                $tipoId = $tipos['marco']->id;
            }

            $agreement = Agreement::firstOrCreate(
                ['resolution_number' => $fila[0]],
                [
                'title' => $fila[0],
                'name' => $fila[3],
                'resolution_number' => $fila[0],
                'institution_id' => $institucion->id,
                'agreement_type_id' => $tipoId, 
                'start_date' => $fila[4],
                'end_date' => $fila[5],
                'status' => 'Vigente'
            ]);

            $codigo = $fila[0];
            $anio = substr($codigo, -4); 
            $rutaRelativa = "convenios/{$anio}/{$codigo}.pdf"; 

            if (Storage::disk('public')->exists($rutaRelativa)) {
                $agreement->documents()->firstOrCreate(
                    ['file_path' => $rutaRelativa],
                    [
                    'name' => 'Doc - ' . ($agreement->resolution_number ?? $agreement->title),
                    'file_path' => $rutaRelativa,
                    'extension' => 'pdf'
                ]);
            }
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
