<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Agreement;
use App\Models\Institution;
use App\Models\AgreementType;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class Convenios2017Seeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        $tipos = [
            'marco' => AgreementType::firstOrCreate(['name' => 'Convenio Marco']),
            'especifico' => AgreementType::firstOrCreate(['name' => 'Convenio Específico']),
            'memorando' => AgreementType::firstOrCreate(['name' => 'Memorando de Entendimiento']),
            'adenda' => AgreementType::firstOrCreate(['name' => 'Adenda']),
        ];
        
        $datos = [
            ['004-2017', 'COMISIÓN PARA EL INTERCAMBIO EDUCATIVO ENTRE EL PERÚ Y LOS ESTADOS UNIDOS DE AMÉRICA (COMISÍON FULBRIGTH)', 'Otros', 'MEMORÁNDUM DE ENTENDIMIENTO QUE SUSCRIBEN LA UNCP Y LA COMISIÓN PARA EL INTERCAMBIO EDUCATIVO ENTRE EL PERÚ Y LOS ESTADOS UNIDOS- COMISIÓN FULBRIGHT', '2017-01-17', '2022-01-17', 'Perú'],
            ['005-2017', 'RED PERUANA DE UNIVERSIDADES', 'Educación', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LAS UNIVERSIDADES FUNDADORAS DE LA RED PERUANA  DE UNIVERSIDADES', '2017-05-20', '2022-05-20', 'Perú'],
            ['007-2017', 'CLÍNCA DENTAL PREMIUM E.I.R.L.', 'Empresa Nacional', 'ADENDA AL CONVENIO INTERINSTITUCIONAL ENTRE LA UNCP Y LA CLÍNICA DENTAL PREMIUM EIRL', '2017-02-02', null, 'Perú'],
            ['008-2017', 'CENTRO INTERNCAIONAL DE LA PAPA', 'Otros', 'CONVENIO MARCO DE COOPERAICÓN INTERINSTITUCIONAL ENTRE LA UNCP Y EL CENTRO INTERNACIONAL DE LA PAPA', '2017-02-16', '2022-02-16', 'Internacional'],
            ['009-2017', 'MINISTERIO DE ENERGÍA Y MINAS', 'Sector Público', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE EL MINISTERIO DE ENERGÍA Y MINAS Y LA UNCP', null, null, 'Perú'],
            ['010-2017', 'UNIVERSIDAD CONTINENTAL', 'Educación', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNCP - FACULTAD DE CIENCIAS FORESTALES Y DEL AMBIENTE Y LA UNIVERSIDAD CONTINENTAL', '2017-03-07', '2020-03-07', 'Perú'],
            ['011-2017', 'UNIVERSIDAD ESTUAL DE CAMPINAS', 'Educación', 'ACUERDO DE COOPERACIÓN ACADÉMICA INTERNACIONAL ENTRE LA UNCP Y LA UNIVERSIDADE  ESTADUAL  DE CAMPINAS', '2016-11-15', null, 'Internacional'],
            ['012-2017', 'AUTORIDAD NACIONAL DEL AGUA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNCP Y LA AUTORIDAD NACIONAL DEL AGUA', '2017-03-17', '2020-03-17', 'Perú'],
            ['014-2017', 'CONCEJO NACIONAL DE CIENCIA, TECNOLOGÍA E INNOVACIÓN TECNOLÓGICA- CONCYTEC', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNCP Y EL CONSEJO NACIONAL DE CIENCIA TECNOLOGÍA E INNOVACIÓN TECNOLÓGICA - CONCYTEC', '2017-04-03', '2020-04-03', 'Perú'],
            ['015-2017', 'ESSALUD', 'Salud', 'CONVENIO MARCO ENTRE EL SEGURO SOCIAL DE SALUD-ESSALUD Y LA UNCP', '2017-03-24', '2020-03-24', 'Perú'],
            ['016-2017', 'UNIVERSIDAD TECNOLÓGICA DE TULA- TEPEJI', 'Educación', 'CONVENIO DE COOPERACIÓN ACADÉMICA E INTERCAMBIO ENTRE LA UNCP Y LA UNIVERSIDAD TECNOLÓGICA DE TULA - TEPEJI', '2017-01-06', '2022-01-06', 'Perú'],
            ['017-2017', 'CENTRO DE EUDCACIÓN BÁSICA ESPECIAL POLIVALENTE DE EL TAMBO - HUANCAYO', 'Otros', 'CONVENIO ENTRE LA UNCP -FACULTAD DE TRABAJO SOCIAL Y EL CENTRO DE EDUCACIÓN BÁSICA ESPECIAL POLIVALENTE DE EL TAMBO - HUANCAYO', null, null, 'Perú'],
            ['018-2017', 'SOCIEDAD DE BENEFIENCIA DE HUANCAYO', 'Otros', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA SOCIEDAD DE BENEFIENCIA DE HUANCAYO', '2017-04-17', '2020-04-17', 'Perú'],
            ['020-2017', 'SAIS TUPAC AMARU LDTA N°1', 'Otros', 'CONVNEIO MARCO DE COOPERACIÓN RECÍPROCA ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA SAIS TUPAC AMARU LDTA N°1', '2017-05-15', '2020-05-15', 'Perú'],
            ['021-2017', 'UNIVERSIDAD FEDERAL RURAL DO RÍO DE JANEIRO (BRASIL)', 'Educación', 'ACUERDO DE COOPERACIÓN ACADÉMICA, CIENTÍFICA Y CULTURAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA UNIVERSIDAD FEDERAL RURAL DO RÍO DE JANEIRO (BRASIL)', '2017-04-27', '2020-04-27', 'Perú'],
            ['022-2017', 'MUNICIPALIDAD PROVINCIAL DE SATIPO', 'Sector Público', 'CONVENIO INTERINSTITUCIONAL ENTRE LA MUNICPALIDAD DESATIPO Y LA UNCP PARA LA FORMULACIÓN DEL PROYECTO DE INVERSIÓN PÚBLICA " CREACIÓN DEL SERVICIO DE COMEDOR UNIVERSITARIO DE LA FACULTAD DE CIENCIA...', null, null, 'Perú'],
            ['023-2017', 'MUNICPALIDAD DISTRITAL DE MOROCOCHA', 'Otros', 'COVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD  DISTRITAL  DE MOROCOCHA', '2017-05-02', '2020-05-02', 'Perú'],
            ['024-2017', 'COMUNIDAD CMAPESINA DE ROCCHAC', 'Comunidades', 'CONVENIO ESPECÍFICO ENTRE LA UNIVERSIDAD NACIONAL DE CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE ROCCOCHAC - DISTRITO DE PARIAHUANCA - PROVINCIA DE HUANCAYO - DEPARTAMENTO DE JUNÍN', '2017-05-22', '2020-05-22', 'Perú'],
            ['025-2017', 'RED ASISTENCIAL DE JUNÍN', 'Salud', 'CONVENIO ESPECÍFICO PARA LA PRESTACIÓN DE SERVICIOS DE SALUD - RED ASITENCIAL DE JUNÍN - UNCP', '2017-05-11', '2018-05-11', 'Perú'],
            ['026-2017', 'ESSSALUD- RED ASISTENCIAL DE JUNÍN', 'Salud', 'CONVENIO ESPECÍFICO ENTRE ESSALUD - RED ASISTENCIAL JUNÍN Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ - FACULTAD DE MEDICINA', '2017-05-18', null, 'Perú'],
            ['027-2017', 'RED DE SALUD JAUJA', 'Salud', 'CONVENIO ESPECÍFICO PARA PRESTACIÓN DE SERVICIOS DE SALUD - RED ASISTENCIAL DE JAUJA - UNCP', '2017-05-11', '2018-05-11', 'Perú'],
            ['028-2017', 'RED DE SALUD DE SATIPO', 'Salud', 'CONVENIO ESPECÍFICO PARA PRESTACIÓN DE SERVICIOS DE SALUD - RED DE SALUD DE SATIPO - UNCP', '2017-05-12', '2018-05-12', 'Perú'],
            ['030-2017', 'INSTITUTO UNIVERSITARIO DE INVESTIGACIÓN DE INGENIERÍA DEL AGUA Y MEDIO AMBIENTE DE LA UNIVERSITAT POLITECNICA DE VALENCIA', 'Educación', 'CONVENIO DE COOPERACIÓN ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL INSTITUTO UNIVERSITARIO DE INVESTIGACIÓN DE INGENIERÍA DEL AGUA Y MEDIO AMBIENTE DE LA UNIVERSITAT POLITECNICA DE VALE...', null, null, 'Perú'],
            ['031-2017', 'INSTITUTO NACIONAL DE ESTADÍSTICA E INFORMÁTICA', 'Educación', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE EL INSTITUTO NACIONAL DE ESTADÍSTICA E INFORMÁTICA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2017-04-21', '2018-04-21', 'Perú'],
            ['032-2017', 'ONG CRECER MYPE PERÚ', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA ONG CRECER MYPE PERÚ', '2017-07-13', '2022-07-13', 'Perú'],
            ['033-2017', 'INSTITUTO TECNOLÓGICO SUPERIOR DE XALAPA - CARRERA DE INGENIERÍA BIOQUÍMICA', 'Educación', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERISNTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y- FACULTAD DE INGENIERÍA QUÍMICA Y EL INSTITUTO TECNOLÓGICO SUPERIOR DE XALAPA - CARRRERA DE...', '2017-03-07', null, 'Perú'],
            ['034-2017', 'INSTITUTO TECNOLÓGICO DE XALAPA', 'Educación', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL INSTITUTO TECNOLÓGICO SUPERIOR DE XALAPA', '2017-03-07', null, 'Perú'],
            ['035-2017', 'INSTITUTO NACIONAL DE INVESTIGACIÓN EN GLACIARES Y ECOSISTEMAS DE MONTAÑA', 'Educación', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL INSTITUTO NACIONAL DE INVESTIGACIÓN DE GLACIARES Y ECOSISITEMAS DE MONTAÑA', '2017-07-10', '2022-07-10', 'Perú'],
            ['036-2017', 'INSTITUTO DE EDUCACIÓN SUPERIOR TECNOLÓGICO PÚBLICO  ASHANINKA', 'Educación', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL INSTITUTO DE EDUCACIÓN SUPERIOR ASHANINKA', '2017-07-11', '2020-07-11', 'Internacional'],
            ['037-2017', 'DIRECCION REGIONAL DE EDICACIÓN JUNÍN', 'Sector Público', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA DIRECCIÓN REGIONAL DE EDUCACIÓN', '2017-07-03', '2022-07-03', 'Perú'],
            ['038-2017', 'COMITÉ DE ADMINISTRACIÓN DE LSO RECURSOS PARA CAPACITACIÓN', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN CELEBRADO ENTRE LE CÓMITE DE ADMINISTRACIÓN DE LOS RECURSOS PARA CAPACITACIÓN - CAREC Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ - HUANCAYO', '2017-09-03', '2019-09-03', 'Perú'],
            ['039-2017', '', 'Otros', 'CONVENIO DE ASOCIACION PARA LA EJECUCIÓN DE PROYECTO', null, null, 'Perú'],
            ['040-2017', 'UNIVERSIDAD PRIVADA DE HUACNAYO FRANKLIN ROOSEVELT SAC', 'Educación', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA UNIVERSIDAD PRIVADA DE HUANCAYO FRANKLIN ROOSEVELT SAC', '2017-09-07', '2019-09-07', 'Perú'],
            ['041-2017', 'MUNICIPALIDAD PRIVINCIAL DE SATIPO', 'Sector Público', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD PROVINCIAL DE SATIPO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', null, null, 'Perú'],
            ['042-2017', 'INNOVATE PERÚ', 'Otros', 'CONVENIO DE ASOCIACIÓN PARA LA EJECUCIÓN DE PROYECTO "DESAROLLO Y ELABORACIÓN DE UN ALIMENTO FUNCIONAL DE CONSERVA DE CUY TIPO CALDO, PARA PACIENTES HOSPITALLARIOS Y AMBULATORIOS VULNERABLES NUTRIC...', null, null, 'Perú'],
            ['043-2017', 'SERVICIO NACIONAL DE ÁREAS NATURALES PROTEGIDAS', 'Sector Público', 'ADENDA AL CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE EL SERVICIO NACIONAL DE ÁREAS NATURALES PROTEGIDAS POR EL ESTADO Y LA UNCP', '2017-07-13', '2021-07-13', 'Perú'],
            ['044-2017', 'GOBIERNO REGIONA LDE JUNÍN', 'Sector Público', 'CONVENIO MARCO DE COOPERACIÓN INTERISNTITUCIONAL ENTRE EL GOBIERNO REGIONAL DE JUNÍN Y LA UNVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2017-09-21', '2022-09-21', 'Perú'],
            ['045-2017', 'MINISTERIO DE LA MUJER Y POBLACIONES VULNERABLES', 'Sector Público', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE EL PROGRAMA NACIONAL CONTRA LA VIOLENCIA FAMILIAR Y SEXUAL DEL MINISTERIO DE LA MUJER Y POBLACIONES VULNERABLES Y LA UNIVERSIDAD NACIONAL DEL CNETRO...', '2017-10-11', '2019-10-11', 'Perú'],
            ['046-2017', 'CENEPRED', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNCP Y EL CENTRO NACIONAL DE ESTIMACIÓN, PREVENCIÓN Y REDUCCIÓN DE RIESGOS', '2017-10-07', '2020-10-07', 'Perú'],
            ['047-2017', 'MINERIA CHINALCO PERÚ S.A.', 'Otros', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNCP Y LA MINERA CHINALCO PERÚ S.A.', '2017-03-01', '2018-03-01', 'Perú'],
            ['048-2017', 'UNIVERSIDAD FEDERAL DE MINAS GENERAIS - BRASIL', 'Educación', 'CONVENIO MARCO ENTRE LA UNIVERSIDAD FEDERAL DE MINAS GENERAIS (UFMG) Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', null, '2022-10-09', 'Perú'],
            ['049-2017', 'I.E. N° 30234 "ROBERTO QUISPE POMALAZA" DEL DISTRITO DE QUILCAS', 'Educación', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNCP Y LA I.E. N° 30234 "ROBERTO QUISPE POMALAZA" DEL DISTRITO DE QUILCAS', '2017-10-20', '2020-10-20', 'Perú'],
            ['050-2017', 'UNIVERSIDAD NACIONAL DE COLOMBIA', 'Universidad Nacional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNCP Y LA UNIVERSIDAD NACIONAL DE COLOMBIA', '2017-11-21', '2022-11-21', 'Perú'],
            ['051-2017', 'MUNICIPALIDAD DISTRITAL DE RÍO NEGRO', 'Sector Público', 'CONVENIO INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD DISTRITAL DE RÍO NEGRO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', null, '2037-12-22', 'Perú'],
            ['052-2017', 'MUNICIPALIDAD PROVINCIAL DE CONCEPCIÓN', 'Sector Público', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD PROVINCIAL DE CONCEPCIÓN Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2017-10-04', '2020-10-04', 'Perú'],
            ['053 -2017', 'AGRONEGOCIOS EL PROGRESO S.A.C.', 'Empresa Nacional', 'CONVENIO DE ASOCIACIÓN PARA LA EJECUCIÓN DE PROYECTO: "INCRMEENTO DE LA PRODUCTIVIDAD DEL CULTIVO DE PIÑAS ANANAS CAMOSUS MD - 2- GOLDEN, POR LA RECUPERACIÓN DE SUELOS CON ZEOLITAS, FERTILIZACIÓN, ...', '2017-11-09', null, 'Perú'],
            ['054-2017', 'MUNICIPALIDAD E SICAYA', 'Sector Público', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD DISTRITAL DE SICAYA Y LA UNCP', null, null, 'Perú'],
            ['055-2017', 'UNIVERSIA PERÚ S.A. - TRABAJANDO PERÚ. S.A.C.', 'Empresa Nacional', 'CONVENIO ENTRE LA UNCP Y UNIVERSIA PERÚ SA- TRABANJADO PERÚ.COM S.A.C.', null, null, 'Perú'],
            ['056-2017', 'CENTRO ODNTOLÓGICO AMERICAN', 'Otros', 'CONVENIO PRIVADO DE SERVICIOS ODONTOLÓGICOS ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y CENTRO MÉDICO ODONTOLÓGCIO AMERICANO S.A.C.', '2017-11-02', null, 'Perú'],
            ['057-2017', 'ASOCIACIÓN DE PRODUCTORES AGROPECUARIOS LOS PROGRESISTAS DE CHUCOS PUCARA
CAMPO VERDE DEL CENTRO SAC', 'Empresa Nacional', 'CONVENIO DE ASOCIACION EN PARTICIPACIÓN CON PRODUCTORES AGROPECUARIOS LOS PROGRESISTAS DE CHUCOS PUCARA CAMPO VERDE DEL CENTRO SAC.', '2017-09-01', null, 'Perú'],
            ['058-2017', 'ASOCIACION EN PARTICIPACIÓN CON PRODUCTORES AGROPECUARIOS LOS TIGRES DE JATUN SUCLLA PUCARA CAMPO VERDE DEL CENTRO SAC.', 'Empresa Nacional', 'CONVENIO DE ASOCIACION EN PARTICIPACIÓN CON PRODUCTORES AGROPECUARIOS LOS TIGRES DE JATUN SUCLLA PUCARA CAMPO VERDE DEL CENTRO SAC.', '2017-09-01', null, 'Perú'],
            ['060-2017', 'ASOCIACION EN PARTICIPACIÓN CON PRODUCTORES AGRICOLAS DE LA SELVA CENTRAL ASHANINKA DEL PERU- CAMPO VERDE DEL CENTRO SAC.', 'Empresa Nacional', 'CONVENIO DE ASOCIACION EN PARTICIPACIÓN CON PRODUCTORES AGRICOLAS DE LA SELVA CENTRAL ASHANINKA DEL PERU- CAMPO VERDE DEL CENTRO SAC.', '2017-09-03', null, 'Perú'],
        ];

        foreach ($datos as $fila) {
            $nombreInstitucion = strtoupper($fila[1]);
            $tipoEstandarizado = $fila[2];
            $pais = $fila[6];

            $institucion = Institution::firstOrCreate(
                ['name' => $nombreInstitucion],
                ['country' => $pais, 'type' => $tipoEstandarizado]
            );

            $nombreLargo = strtoupper($fila[3]);
            
            if (str_contains($nombreLargo, 'MEMORANDO')) {
                $tipoId = $tipos['memorando']->id;
            } elseif (str_contains($nombreLargo, 'ADENDA')) {
                $tipoId = $tipos['adenda']->id;
            } elseif (str_contains($nombreLargo, 'ESPECIFICO') || str_contains($nombreLargo, 'ESPECÍFICO')) {
                $tipoId = $tipos['especifico']->id;
            } else {
                $tipoId = $tipos['marco']->id;
            }

            $agreement = Agreement::firstOrCreate(
                ['resolution_number' => $fila[0]],
                [
                'title' => $fila[0],
                'name' => $fila[3],
                'resolution_number' => $fila[0],
                'institution_id' => $institucion->id,
                'agreement_type_id' => $tipoId, 
                'start_date' => $fila[4],
                'end_date' => $fila[5],
                'status' => 'Vigente'
            ]);

            $codigo = $fila[0];
            $anio = substr($codigo, -4); 
            $rutaRelativa = "convenios/{$anio}/{$codigo}.pdf"; 

            if (Storage::disk('public')->exists($rutaRelativa)) {
                $agreement->documents()->firstOrCreate(
                    ['file_path' => $rutaRelativa],
                    [
                    'name' => 'Doc - ' . ($agreement->resolution_number ?? $agreement->title),
                    'file_path' => $rutaRelativa,
                    'extension' => 'pdf'
                ]);
            }
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
