<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Agreement;
use App\Models\Institution;
use App\Models\AgreementType;
use Illuminate\Support\Facades\DB;

class Convenios2022Seeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // 1. Crear los 3 tipos de alianza oficiales
        $tipos = [
            'marco' => AgreementType::firstOrCreate(['name' => 'Convenio Marco']),
            'especifico' => AgreementType::firstOrCreate(['name' => 'Convenio Específico']),
            'memorando' => AgreementType::firstOrCreate(['name' => 'Memorando de Entendimiento']),
        ];
        
        // Estructura: [0: Código, 1: Institución, 2: Tipo de Institución, 3: Nombre del convenio, 4: Fecha Inicio, 5: Fecha Fin, 6: País]
        $datos = [
            ['001-2022', 'RED NACIONAL DE CATI EN PERÚ', 'Otros', 'ADENDA N° 2 AL CONVENIO DE COLABORACIÓN PARA EL ESTABLECIMIENTO DE UN CENTRO DE APOYO A LA TECNOLOGÍA Y LA INNOVACIÓN (CATI) EN LA UNCP COMO INSTITUCIÓN INTEGRANTE DE LA RED NACIONAL DE CATI EN PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['002-2022', 'INSTITUCION EDUCATIVA UNIÓN LATINO INNOVA', 'Institución Educativa', 'CONVENIO ESPECÍFICO ENTRE LA FACULTAD DE TRABAJO SOCIAL DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA INSTITUCION EDUCATIVA UNIÓN LATINO INNOVA', '2022-01-01', '2025-01-01', 'Perú'],
            ['003-2022', 'DESCOCENTRO', 'Otros', 'CONVENIO DE ASOCIACIÓN PARA LA EJECUCIÓN DE PROYECTO ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y DESCOCENTRO', '2022-01-01', '2025-01-01', 'Perú'],
            ['004-2022', 'OSITRAN', 'Otros', 'ADENDA N° 1 AL CONVENIO DE PRÁCTICAS PREPROFESIONALES N° 013-2021-OSITRAN', '2022-01-01', '2025-01-01', 'Perú'],
            ['005-2022', 'MUNICIPALIDAD PROVINCIAL DE SATIPO', 'Municipalidad', 'CONVENIO MARCO DE COOPERCIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACINAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD PROVINCIAL DE SATIPO', '2022-01-01', '2025-01-01', 'Perú'],
            ['006-2022', 'ENGIE ENERGÍA PERÚ', 'Empresa Nacional', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA EMPRESA ENGIE ENERGÍA PERÚ Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ-BECAS ENGIE, MUJERES CON ENERGÍA', '2022-01-01', '2025-01-01', 'Perú'],
            ['007-2022', 'FUNDACIÓN SER MAESTRO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN ACADÉMICA ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PRÚ Y LA FUNDACIÓN SER MAESTRO Y LA FACULTAD DE ARQUITECTURA', '2022-01-01', '2025-01-01', 'Perú'],
            ['008-2022', 'MUNICIPALIDAD DISTRITAL DE SAN PEDRO DE CAJAS', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL  CENTRO DEL PERÚ Y LA MUNICIPALIDAD DISTRITAL DE SAN PEDRO DE CAJAS DE PROVINCIA DE TARMA', '2022-01-01', '2025-01-01', 'Perú'],
            ['009-2022', 'COMUNIDAD CAMPESINA DE YAROCA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL  CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE YAROCA DE PROVINCIA DE TARMA', '2022-01-01', '2025-01-01', 'Perú'],
            ['010-2022', 'COMUNIDAD CAMPESINA DE URAUCHOC', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE URAUCHOC DE PROVINCIA DE TARMA', '2022-01-01', '2025-01-01', 'Perú'],
            ['011-2022', 'INSTITUCIÓN EDUCATIVA INDUSTRIAL N° 32', 'Institución Educativa', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA INSTITUCIÓN EDUCATIVA INDUSTRIAL N° 32 DE PROVINCIA DE TARMA', '2022-01-01', '2025-01-01', 'Perú'],
            ['012-2022', 'COMUNIDAD CAMPESINA DE PALCAMAYO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE PALCAMAYO DE PROVINCIA DE TARMA', '2022-01-01', '2025-01-01', 'Perú'],
            ['013-2022', 'COMUNIDAD CAMPESINA ERAHUAY', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA ERAHUAY DE PROVINCIA DE TARMA', '2022-01-01', '2025-01-01', 'Perú'],
            ['014-2022', 'COMUNIDAD CAMPESINA HUAYLAHUICHAN', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA HUAYLAHUICHAN DE PROVINCIA DE TARMA', '2022-01-01', '2025-01-01', 'Perú'],
            ['015-2022', 'COMUNIDAD CAMPESINA SAN CRISTOBAL DE PACCHAC', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA SAN CRISTOBAL DE PACCHAC DE PROVINCIA DE TARMA', '2022-01-01', '2025-01-01', 'Perú'],
            ['016-2022', 'COMUNIDAD CAMPESINA DE YURACMAYO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE YURACMAYO DE PROVINCIA DE TARMA', '2022-01-01', '2025-01-01', 'Perú'],
            ['017-2022', 'COMUNIDAD CAMPESINA DE SAN ANTONIO DE ATAQUERO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE SAN ANTONIO DE ATAQUERO DE PROVINCIA DE TARMA', '2022-01-01', '2025-01-01', 'Perú'],
            ['018-2022', 'COMUNIDAD CAMPESINA DE TUPIN', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE TUPIN DE PROVINCIA DE TARMA', '2022-01-01', '2025-01-01', 'Perú'],
            ['019-2022', 'COMUNIDAD CAMPESINA DE NINATAMBO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE NINATAMBO DE PROVINCIA DE TARMA', '2022-01-01', '2025-01-01', 'Perú'],
            ['020-2022', 'COMUNIDAD CAMPESINA DE COCHAS', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE COCHAS DE PROVINCIA DE TARMA', '2022-01-01', '2025-01-01', 'Perú'],
            ['021-2022', 'MUNICIPALIDAD DISTRITAL DE CHUPURO', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD DISTRITAL DE CHUPURO Y  LA UNIVERSIDAD NACIONAL DEL  CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['022-2022', 'MUNICIPALIDAD DISTRITAL DE CARHUACALLANGA', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD DISTRITAL DE CARHUACALLANGA Y  LA UNIVERSIDAD NACIONAL DEL  CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['023-2022', 'INSTITUTO DE EDUCACIÓN SUPERIOR TECNOLÓGICO PÚBLICO ASHANINKA', 'Institución Educativa', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL INSTITUTO DE EDUCACIÓN SUPERIOR TECNOLÓGICO PÚBLICO ASHANINKA', '2022-01-01', '2025-01-01', 'Perú'],
            ['024-2022', 'SOCIEDAD DE BENEFICENCIA DE HUANCAYO', 'Otros', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA SOCIEDAD DE BENEFICENCIA DE HUANCAYO', '2022-01-01', '2025-01-01', 'Perú'],
            ['025-2022', 'SEGURO SOCIAL DE SALUD - ESSALUD', 'Salud', 'CONVENIO MARCO ENTRE EL SEGURO SOCIAL DE  SALUD - ESSALUD  Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['026-2022', 'PODER JUDICIAL - CORTE SUPERIOR DE JUSTICIA DE JUNÍN', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE EL PODER JUDICIAL - CORTE SUPERIOR DE JUSTICIA DE JUNÍN Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['027-2022', 'HOSPITAL DOMINGO OLAVEGOYA DE JAUJA', 'Salud', 'ADENDA N° 001 A LA RENOVACIÓN DE CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTE -  ASISTENCIAL ENTRE EL HOSPITAL DOMINGO OLAVEGOYA DE JAUJA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['028-2022', 'RED DE SALUD DEL VALLE DEL MANTARO', 'Salud', 'PRIMERA ADENDA AL CONVENIO N° 002-MINSA CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA RED DE SALUD DEL VALLE DEL MANTARO Y LA FACULTAD DE MEDICINA HUMANA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['029-2022', 'RED ASISTENCIAL JUNIN', 'Salud', 'CONVENIO ESPECÍFICO ENTRE LA RED ASISTENCIAL JUNIN Y LA FACULTAD DE ENFERMERÍA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['030-2022', 'UNIVERSIDAD NACIONAL JOSÉ MARÍA ARGUEDAS', 'Universidad Nacional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL JOSÉ MARÍA ARGUEDAS Y  LA UNIVERSIDAD NACIONAL DEL  CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['031-2022', 'EMPRESA SIERRA POLI SAC', 'Empresa Nacional', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ, LA FACULTAD DE ZOOTECNIA Y LA EMPRESA SIERRA POLI SAC.', '2022-01-01', '2025-01-01', 'Perú'],
            ['032-2022', 'COMUNIDAD CAMPESINA DE CULLHUAS', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE CULLHUAS', '2022-01-01', '2025-01-01', 'Perú'],
            ['033-2022', 'MUNICIPALIDAD DE CHACAPAMPA', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD DE CHACAPAMPA', '2022-01-01', '2025-01-01', 'Perú'],
            ['034-2022', 'MINISTERIO DE SALUD, GOBIERNO REGIONAL DE JUNÍN (DIRESA)', 'Salud', 'CONVENIO MARCO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE EL MINISTERIO DE SALUD, GOBIERNO REGIONAL DE JUNÍN (DIRESA)  Y LA UNIVERSIDAD NACIONAL DEL CENTRO DELPERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['035-2022', 'MINISTERIO DE SALUD, GOBIERNO REGIONAL DE HUANCAVELICA', 'Salud', 'CONVENIO MARCO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE EL MINISTERIO DE SALUD, GOBIERNO REGIONAL DE HUANCAVELICA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DELPERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['036-2022', 'MUNICIPALIDAD DISTRITAL DE CHUPURO', 'Municipalidad', 'CONVENIO MARCO DE COLABORACIÓN ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ - FACULTAD DE AGRONOMÍA Y LA MUNICIPALIDAD DISTRITAL DE CHUPURO', '2022-01-01', '2025-01-01', 'Perú'],
            ['037-2022', 'UNIVERSIDAD PERUANA LOS ANDES - UPLA', 'Universidad Privada', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ, LA FACULTAD DE TRABAJO SOCIAL Y LA UNIVERSIDAD PERUANA LOS ANDES - UPLA', '2022-01-01', '2025-01-01', 'Perú'],
            ['038-2022', 'RDJ INGENIEROS SAC', 'Empresa Nacional', 'CONVENIO ESPECÍFICO ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y RDJ INGENIEROS SAC PARA LA EJECUCIÓN DE PROYECTO', '2022-01-01', '2025-01-01', 'Perú'],
            ['039-2022', 'LECKER PREMIUM BIER SAC', 'Empresa Nacional', 'CONVENIO ESPECÍFICO ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LECKER PREMIUM BIER SAC PARA LA EJECUCIÓN DE PROYECTO', '2022-01-01', '2025-01-01', 'Perú'],
            ['040-2022', 'UNIDAD EJECUTORA N°118 MEJORAMIENTO DE LA CALIDAD DE EDUCACIÓN BÁSICA Y SUPERIOR', 'Otros', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIDAD EJECUTORA N°118 MEJORAMIENTO DE LA CALIDAD DE EDUCACIÓN BÁSICA Y SUPERIOR Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['041-2022', 'MINISTERIO DE SALUD, GOBIERNO REGIONAL DEL CALLAO', 'Salud', 'CONVENIO MARCO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE EL MINISTERIO DE SALUD, GOBIERNO REGIONAL DEL CALLAO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DELPERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['042-2022', 'INSTITUCIÓN EDUCATIVA SEIS DE AGOSTO - JUNÍN', 'Institución Educativa', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA EMBLEMÁTICA INSTITUCIÓN EDUCATIVA SEIS DE AGOSTO - JUNÍN', '2022-01-01', '2025-01-01', 'Perú'],
            ['043-2022', 'UNIVERSIDAD AUTÓNOMA METROPOLITANA', 'Universidad Internacional', 'CONVENIO ESPECÍFICO DE COOPERACIÓN PARA LA MOVILIDAD DEL ALUMNADO ENTRE LA UNIVERSIDAD AUTÓNOMA METROPOLITANA, DE LOS ESTADOS UNIDOS MEXICANOS Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'México'],
            ['044-2022', 'UNIVERSIDAD AUTÓNOMA METROPOLITANA', 'Universidad Internacional', 'CONVENIO GENERAL DE COOPERACIÓN ENTRE LA UNIVERSIDAD AUTÓNOMA METROPOLITANA, DE LOS ESTADOS UNIDOS MEXICANOS Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'México'],
            ['045-2022', 'INSTITUCIÓN EDUCATIVA SALESIANO DON BOSCO DE HUANCAYO', 'Institución Educativa', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ - FACULTAD DE TRABAJO SOCIAL Y LA INSTITUCIÓN EDUCATIVA SALESIANO DON BOSCO DE HUANCAYO', '2022-01-01', '2025-01-01', 'Perú'],
            ['046-2022', 'CAJA RURAL DE AHORRO Y CRÉDITO DEL CENTRO-HUANCAYO', 'Empresa Nacional', 'CONVENIO DE PRESTAMOS PERSONALES ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA CAJA RURAL DE AHORRO Y CRÉDITO DEL CENTRO-HUANCAYO', '2022-01-01', '2025-01-01', 'Perú'],
            ['047-2022', 'UNIVERSIDAD NACIONAL AMAZÓNICA DE MADRE DE DIOS-UNAMAD', 'Universidad Nacional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ-UNCP Y LA UNIVERSIDAD NACIONAL AMAZÓNICA DE MADRE DE DIOS-UNAMAD', '2022-01-01', '2025-01-01', 'Perú'],
            ['048-2022', 'UNIVERSIDAD NACIONAL DE FRONTERA', 'Universidad Nacional', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERINSTITUCIONAL PARA EL "DESARROLLO DE ACCIONES ACADÉMICAS Y DE INVESTIGACIÓN CIENTÍFICA" ENTRE LA FACULTAD DE INGENIERÍA DE INDUSTRIAS ALIMENTARIAS Y BIOTECNOLOGÍA DE LA UNIVERSIDAD NACIONAL DE FRONTERA Y LA FACULTAD DE INGENIERÍA EN INDUSTRIAS ALIMENTARIAS DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['049-2022', 'UNIVERSIDAD NACIONAL DE FRONTERA', 'Universidad Nacional', 'CONVENIO MARCO COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DE FRONTERA  Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['050-2022', 'OSITRAN', 'Otros', 'AGENDA N°03 AL CONVENIO DE PRÁCTICAS PREPROFESIONALES N° 013-2021-OSITRAN', '2022-01-01', '2025-01-01', 'Perú'],
            ['051-2022', 'RED ASISTENCIAL JUNÍN', 'Salud', 'CONVENIO ESPECÍFICO ENTRE LA RED ASISTENCIAL JUNÍN Y LA FACULTAD DE CIENCIAS DE LA ADMINISTRACIÓN DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['052-2022', 'RED ASISTENCIAL JUNÍN', 'Salud', 'CONVENIO ESPECÍFICO ENTRE LA RED ASISTENCIAL JUNÍN Y LA FACULTAD DE MEDICINA HUMANA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['053-2022', 'RED ASISTENCIAL JUNÍN', 'Salud', 'CONVENIO ESPECÍFICO ENTRE LA RED ASISTENCIAL JUNÍN Y LA FACULTAD DE TRABAJO SOCIAL DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['054-2022', 'DIRECCIÓN REGIONAL DE AGRICULTURA JUNÍN', 'Gobierno Regional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL QUE CELEBRAN LA DIRECCIÓN REGIONAL DE AGRICULTURA JUNÍN Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['055-2022', 'EMPRESA MISKY FOOD ANÓNIMA CERRADA', 'Empresa Nacional', 'CONVENIO ESPECÍFICO ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA EMPRESA MISKY FOOD ANÓNIMA CERRADA PARA LA EJECUCIÓN DEL PROYECTO', '2022-01-01', '2025-01-01', 'Perú'],
            ['056-2022', 'UNIVERSIDAD NACIONAL DE JAÉN', 'Universidad Nacional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA UNIVERSIDAD NACIONAL DE JAÉN', '2022-01-01', '2025-01-01', 'Perú'],
            ['057-2022', 'COMUNIDAD CAMPESINA DE CHONGOS ALTO', 'Otros', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE CHONGOS ALTO', '2022-01-01', '2025-01-01', 'Perú'],
            ['058-2022', 'INSTITUCIÓN EDUCATIVA JOSÉ CARLOS MARIÁTEGUI-HUANCAYO', 'Institución Educativa', 'CONVENIO ESPECÍFICO ENTRE LA FACULTAD DE TRABAJO SOCIAL DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA INSTITUCIÓN EDUCATIVA JOSÉ CARLOS MARIÁTEGUI-HUANCAYO', '2022-01-01', '2025-01-01', 'Perú'],
            ['059-2022', 'EMPRESA UEA COMPAÑÍA MINERA MARMOLES SCRL', 'Empresa Nacional', 'CONVENIO DE COOPERACIÓN TÉCNICA INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA EMPRESA UEA COMPAÑÍA MINERA MARMOLES SCRL', '2022-01-01', '2025-01-01', 'Perú'],
            ['060-2022', 'COMUNIDAD NATIVA DE TEORIA-MAZAMARI', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD NATIVA DE TEORIA-MAZAMARI', '2022-01-01', '2025-01-01', 'Perú'],
            ['061-2022', 'INSTITUTO NACIONAL DE INVESTIGACIÓN EN GLACIARES Y ECOSISTEMAS DE MONTAÑA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTIUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL INSTITUTO NACIONAL DE INVESTIGACIÓN EN GLACIARES Y ECOSISTEMAS DE MONTAÑA', '2022-01-01', '2025-01-01', 'Perú'],
            ['062-2022', 'RED DE SALUD DE CHANCHAMAYO', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE LA RED DE SALUD DE CHANCHAMAYO Y LA FACULTAD DE ENFERMERÍA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['063-2022', 'HOSTIPAL REGIONAL DOCENTE CLÍNICO - QUIRÚRGICO DANIEL ALCIDES CARRION', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE EL HOSTIPAL REGIONAL DOCENTE CLÍNICO - QUIRÚRGICO DANIEL ALCIDES CARRION Y LA FACULTAD DE ENFERMERÍA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['064-2022', 'RED DE SALUD DE SATIPO', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE LA RED DE SALUD DE SATIPO Y LA FACULTAD DE ENFERMERÍA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['065-2022', 'COMUNIDAD CAMPESINA DE HUAMANCACA GRANDE', 'Otros', 'CONVENIO MARCO DE LA COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÙ  Y LA COMUNIDAD CAMPESINA DE HUAMANCACA GRANDE', '2022-01-01', '2025-01-01', 'Perú'],
            ['066-2022', 'MINISTERIO DE ENERGÌA Y MINAS', 'Otros', 'CONVENIO MARCO DE LA COLABORACIÒN INTERINSTITUCIONAL ENTRE EL MINISTERIO DE ENERGÌA Y MINAS Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÙ CON LA PARTICIPACIÒN DEL CONSEJO DE ADMINISTRACIÒN DE RECURSOS PARA LA CAPACITACIÒN EN ELECTRICIDAD (CARELEC)', '2022-01-01', '2025-01-01', 'Perú'],
            ['067-2022', 'INSTITUTO NACIONAL DE DEFENSA DE LA COMPERENCIA Y DE LA PROTECCIÓN DE LA PROPIEDAD INTELECTUAL - INDECOPI', 'Otros', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL INSTITUTO NACIONAL DE DEFENSA DE LA COMPERENCIA Y DE LA PROTECCIÓN DE LA PROPIEDAD INTELECTUAL - INDECOPI', '2022-01-01', '2025-01-01', 'Perú'],
            ['068-2022', 'UNIVERSIDAD DEL PACÍFICO', 'Universidad Privada', 'CONVENIO ESPECÍFICO DE COOPERACIÓN ACADÉMICA ENTRE LA UNIVERSIDAD DEL PACÍFICO Y UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2022-01-01', '2025-01-01', 'Perú'],
            ['069-2022', 'COMUNIDAD MUNICIPAL DEL NORTE DEL VRAEM', 'Otros', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD MUNICIPAL DEL NORTE DEL VRAEM', '2022-01-01', '2025-01-01', 'Perú'],
        ];

        foreach ($datos as $fila) {
            
            $nombreInstitucion = strtoupper($fila[1]);
            $tipoInstitucion = $fila[2];
            $pais = $fila[6];

            // Buscar o crear la institución
            $institucion = Institution::firstOrCreate(
                ['name' => $nombreInstitucion],
                ['country' => $pais, 'type' => $tipoInstitucion]
            );

            // Asignar el ID del tipo de convenio
            $nombreLargo = strtoupper($fila[3]);
            
            if (str_contains($nombreLargo, 'MEMORANDO')) {
                $tipoId = $tipos['memorando']->id;
            } elseif (str_contains($nombreLargo, 'ESPECIFICO') || str_contains($nombreLargo, 'ESPECÍFICO') || str_contains($nombreLargo, 'ADENDA')) {
                $tipoId = $tipos['especifico']->id; 
            } else {
                $tipoId = $tipos['marco']->id;
            }

            // Crear el convenio
            // 1. Creamos el convenio y lo guardamos en una variable
            $agreement = Agreement::create([
                'title' => $fila[0],
                'name' => $fila[3],
                'resolution_number' => $fila[0],
                'institution_id' => $institucion->id,
                'agreement_type_id' => $tipoId, 
                'start_date' => $fila[4],
                'end_date' => $fila[5],
                'status' => 'Vigente'
            ]);

            // 2. Lógica actualizada para buscar en subcarpetas por año
            $codigo = $fila[0]; // Ej: '001-2024'
            
            // Extraemos los últimos 4 caracteres del código para obtener el año (ej: '2024')
            $anio = substr($codigo, -4); 
            
            // Armamos la ruta incluyendo la carpeta del año
            $rutaRelativa = "convenios/{$anio}/{$codigo}.pdf"; 

            // Verificamos si existe y lo guardamos
            if (\Illuminate\Support\Facades\Storage::disk('public')->exists($rutaRelativa)) {
                $agreement->documents()->create([
                    'name' => 'Doc - ' . ($agreement->resolution_number ?? $agreement->title),
                    'file_path' => $rutaRelativa,
                    'extension' => 'pdf'
                ]);
            }
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}