<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Agreement;
use App\Models\Institution;
use App\Models\AgreementType;
use Illuminate\Support\Facades\DB;

class Convenios2023Seeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // 1. Crear los 3 tipos de alianza oficiales
        $tipos = [
            'marco' => AgreementType::firstOrCreate(['name' => 'Convenio Marco']),
            'especifico' => AgreementType::firstOrCreate(['name' => 'Convenio Específico']),
            'memorando' => AgreementType::firstOrCreate(['name' => 'Memorando de Entendimiento']),
        ];
        
        // Estructura: [0: Código, 1: Institución, 2: Tipo de Institución, 3: Nombre del convenio, 4: Fecha Inicio, 5: Fecha Fin, 6: País]
        $datos = [
            ['001-2023', 'ENGIE ENERGÍA PERÚ S.A.', 'Empresa Nacional', 'ADENDA N°01 AL CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE ENGIE ENERGÍA PERÚ S.A. Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ BECAS ENGIE, MUJERES EN ENERGÍA', '2023-01-01', '2026-12-31', 'Perú'],
            ['002-2023', 'MUNICIPALIDAD DISTRITAL DE ULCUMAYO', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD DISTRITAL DE ULCUMAYO PROVINCIA DE JUNÍN REGIÓN JUNÍN Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-01-02', '2025-01-02', 'Perú'],
            ['003-2023', 'COMUNIDADES CAMPESINAS DE LA ZONA SUR, PAZOS, HUARIBAMBA, ÑAHUINPUQUIO, ACOSTAMBO, PICHOS, QUISHUAR Y SALCABAMBA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LAS COMUNIDADES CAMPESINAS DE LA ZONA SUR, PAZOS, HUARIBAMBA, ÑAHUINPUQUIO, ACOSTAMBO, PICHOS, QUISHUAR Y SALCABAMBA.', '2023-01-14', '2028-01-14', 'Perú'],
            ['004-2023', 'UNIVERSIDAD NACIONAL AUTÓNOMA DE TAYACAJA DANIEL HERNÁNDEZ MORILLO', 'Universidad Nacional', 'CONVENIO MARCO DE COLABORACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA UNIVERSIDAD NACIONAL AUTÓNOMA DE TAYACAJA DANIEL HERNÁNDEZ MORILLO.', '2023-01-23', '2028-01-23', 'Perú'],
            ['005-2023', 'CÁMARA DE COMERCIO DE HUANCAYO', 'Empresa Nacional', 'CONVENIO ESPECÍFICO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA CÁMARA DE COMERCIO DE HUANCAYO', '2023-01-01', '2024-01-01', 'Perú'],
            ['006-2023', 'CAJA MUNICIPAL DE AHORRO Y CRÉDITO DE HUANCAYO S.A.', 'Empresa Nacional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA CAJA MUNICIPAL DE AHORRO Y CRÉDITO DE HUANCAYO S.A.', '2023-02-01', '2026-02-01', 'Perú'],
            ['007-2023', 'EMPRESA SIERRA POLI S.A.C.', 'Empresa Nacional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA EMPRESA SIERRA POLI S.A.C.', '2023-02-01', '2028-02-01', 'Perú'],
            ['008-2023', 'MUNICIPALIDAD DISTRITAL DE COCHAS', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD DISTRITAL DE COCHAS', '2023-02-02', '2026-02-02', 'Perú'],
            ['009-2023', 'RED PRESTACIONAL REBAGLIATI', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN ENTRE LA RED PRESTACIONAL REBAGLIATI Y LA FACULTAD DE MEDICINA HUMANA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-02-27', '2025-07-04', 'Perú'],
            ['010-2023', 'MINISTERIO DE SALUD', 'Salud', 'CONVENIO MARCO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE EL MINISTERIO DE SALUD  Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-03-03', '2027-03-03', 'Perú'],
            ['011-2023', 'COMUNIDAD CAMPESINA DE ACOLLA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE ACOLLA', '2023-03-07', '2025-03-07', 'Perú'],
            ['012-2023', 'FUNDACIÓN UNIVERSITARIA MONSERRATE', 'Universidad Internacional', 'CONVENIO MARCO DE COOPERACIÓN INSTITUCIONAL ENTRE LA FUNDACIÓN UNIVERSITARIA MONSERRATE Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-03-14', '2026-03-14', 'Colombia'],
            ['013-2023', 'EMPRESA MAKCROMF - PROINNOVATE', 'Empresa Nacional', 'CONVENIO DE ASOCIACIÓN PARA LA EJECUCIÓN DE PROYECTO', '2023-03-20', null, 'Perú'],
            ['014-2023', 'COMUNIDAD CAMPESINA DE HUAYCHULA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE HUAYCHULA', '2023-03-23', '2026-03-23', 'Perú'],
            ['015-2023', 'HOSPITAL REGIONAL DOCENTE MATERNO INFANTIL EL CARMEN', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE EL HOSPITAL REGIONAL DOCENTE MATERNO INFANTIL EL CARMEN Y LA FACULTAD DE ENFERMERÍA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-03-27', '2023-03-27', 'Perú'],
            ['016-2023', 'COMUNIDAD CAMPESINA DE MUQUIYAUYO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE MUQUIYAUYO', '2023-03-30', '2025-03-30', 'Perú'],
            ['017-2023', 'MUNICIPALIDAD DISTRITAL DE QUILCAS', 'Municipalidad', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD DISTRITAL DE QUILCAS', '2023-03-31', '2026-03-31', 'Perú'],
            ['018-2023', 'COMUNIDAD CAMPESINA DE SAN JERÓNIMO DE TUNÁN', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE SAN JERÓNIMO DE TUNÁN', '2023-03-01', '2026-03-01', 'Perú'],
            ['019-2023', 'FUNDACIÓN PARA EL DESARROLLO DEL CENTRO DEL PERÚ - FUDEC', 'Otros', 'CONVENIO ESPECÍFICO DE COOPERACIÓN ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA FUNDACIÓN PARA EL DESARROLLO DEL CENTRO DEL PERÚ SOBRE LA PLANTA CONCENTRADORA DE MIRELARES "HUARI"', '2023-06-05', '2026-06-05', 'Perú'],
            ['020-2023', 'MUNICIPALIDAD DISTRITAL DE CHINCHIHUASI', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD DISTRITAL DE CHINCHIHUASI- CHURCAMPA HUANCAVELICA', '2023-06-27', '2026-06-27', 'Perú'],
            ['021-2023', 'HOSPITAL REGIONAL DOCENTE MATERNO INFANTIL "EL CARMEN "', 'Salud', 'CONVENIO ESPECIFICO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE EL HOSPITAL REGIONAL DOCENTE MATERNO INFANTIL "EL CARMEN " Y LA FACULTAD DE MEDICINA HUMANA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU', '2023-05-09', '2026-05-09', 'Perú'],
            ['022-2023', 'BANCO BBVA PERU', 'Empresa Nacional', 'CONVENIO PARA EL OTORGAMIENTO DE PRESTAMOS PERSONALES BAJO LA MODALIDAD DE DESCUENTO POR PLANILLA-INSTITUCION PUBLICA (SIN FIANZA)', null, null, 'Perú'],
            ['023-2023', 'INSTITUCION DE EDUCACION SUPERIOR PEDAGOGICO PRIVADO "JUAN ENRIQUE PESTALOZZI"', 'Otros', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA INSTITUCION DE EDUCACION SUPERIOR PEDAGOGICO PRIVADO "JUAN ENRIQUE PESTALOZZI" Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU HUANCAYO', '2023-05-09', '2024-05-09', 'Perú'],
            ['024-2023', 'UNIDAD DE GESTION EDUCATIVA LOCAL TARMA', 'Otros', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIDAD DE GESTION EDUCATIVA LOCAL TARMA Y LA FACULTAD DE CIENCIAS APLICADAS DE LA UNCP-TARMA', '2023-06-21', '2026-06-21', 'Perú'],
            ['025-2023', 'COMUNIDAD CAMPESINA DE CANAYCA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE CANAYCA JUNTO A LOS ANEXOS DE MARISCAL CACERE, LEONCIO PRADO, HUAYTAPAMPA Y LA MUNICIPALIDAD DISTRITAL DE CONAYCA-HUANCAVELICA', '2023-06-22', '2025-06-22', 'Perú'],
            ['026-2023', 'COMUNIDAD CAMPESINA DE PUMARANRA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE PUMARANRA, DISTRITO DE PAUCARA PROVINCIA DE ACOBAMBA- HUANCAVELICA', '2023-06-21', '2026-06-21', 'Perú'],
            ['027-2023', 'COMUNIDAD CAMPESINA DE ANGASMAYO', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE ANGASMAYO', '2023-06-27', '2025-06-27', 'Perú'],
            ['028-2023', 'MUNICIPALIDAD DISTRITAL DE PACHAMARCA', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONALIDAD ENTRE LA UNIVERSIDAD NACIONAL DEL PERU Y LA MUNICIPALIDAD DISTRITAL DE PACHAMARCA-CHURCAMPA HUANCAVELICA', '2023-06-14', '2026-06-14', 'Perú'],
            ['029-2023', 'MUNICIPALIDAD DISTRITAL DE PANGOA', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y MUNICIPALIDAD DISTRITAL DE PANGOA', '2023-06-23', '2025-06-23', 'Perú'],
            ['030-2023', 'MUNICIPALIDAD DISTRITAL DE PAUCARBAMBA', 'Municipalidad', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU, LA  MUNICIPALIDAD DISTRITAL DE PAUCARBAMBA Y LA COMUNIDAD CAMPESINA DE PACHAMARCA', '2023-06-09', '2026-06-09', 'Perú'],
            ['031-2023', 'COMUNIDAD CAMPESINA DE PUCUCHO DE EL MANTARO', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE PUCUCHO DE EL MANTARO', '2023-05-31', '2025-05-31', 'Perú'],
            ['032-2023', 'MUNICIPALIDADES DE LA ZONA VALLE PAMPAS', 'Municipalidad', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LAS MUNICIPALIDADES DE LA ZONA VALLE PAMPAS,PAMPAS TAYACAJA, ACRAQUIA, AHUAYCHA, DANIEL HERNÁNDEZ, SANTIAGO DE TUCUMA, COLCABAMBA,QUICHUAS', '2023-05-29', '2026-05-29', 'Perú'],
            ['033-2023', 'MUNICIPALIDAD DISTRITAL DE CULLHUAS', 'Municipalidad', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL ÉRÚ Y LA MUNICIPALIDAD DISTRITAL DE CULLHUAS', '2023-04-19', '2026-04-19', 'Perú'],
            ['034-2023', 'MUNICIPALIDAD DISTRITAL DE LLOCLLAPAMPA', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LAS UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICILPALIDAD DISTRITAL DE LLOCLLAPAMPA DE LA PROVINCIA DE JAUJA', '2023-05-08', '2027-05-08', 'Perú'],
            ['035-2023', 'COMUNIDAD CAMPESINA DE SICAYA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE SICAYA', '2023-05-16', '2025-05-16', 'Perú'],
            ['036-2023', 'DISTRITOS DE SAN MARCOS DE ROCCHAC, SALCAHUAI, LAMBRAS, TINTAYPUNCU, ROBLE Y SURCUBAMBA', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONLA DEL CENTRO DEL PERÚ Y LOS DISTRITOS DE SAN MARCOS DE ROCCHAC, SALCAHUAI, LAMBRAS, TINTAYPUNCU, ROBLE Y SURCUBAMBA', '2023-05-17', '2026-05-17', 'Perú'],
            ['037-2023', 'COMUNIDAD CAMPESINA DE TODOS LOS SANTOS', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE TODOS LOS SANTOS', '2023-05-23', '2026-05-23', 'Perú'],
            ['038-2023', 'COMUNIDAD DE SAN AGUSTÍN', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD DE SAN AGUSTÍN', '2023-05-08', '2026-05-08', 'Perú'],
            ['039-2023', 'GOBIERNO REGIONAL DE JUNIN', 'Gobierno Regional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL GOBIERNO REGIONAL DE JUNIN', '2023-05-22', '2028-05-22', 'Perú'],
            ['040-2023', 'EMPRESA GOLDEN DUCK MINING S.A.C.', 'Empresa Nacional', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA EMPRESA GOLDEN DUCK MINING S.A.C.', '2023-05-11', '2025-05-11', 'Perú'],
            ['041-2023', 'SOCIEMC', 'Otros', 'Memorándum de Entendimineto entre SOCIEMC y La Universidad Nacional del Centro del Perú', '2023-05-01', '2024-05-01', 'Perú'],
            ['042-2023', 'UNIVERSIDAD NACIONAL DE ARTE DIEGO QUISPE TITO DEL CUSCO', 'Universidad Nacional', 'CONVENIO MARCO DE COPERACIÓN ACADÉMICA, CIENTÍFICA Y CULTURAL QUE CELEBREAN LA UNIVERSIDAD NACIONAL DE ARTE DIEGO QUISPE TITO DEL CUSCO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-06-14', '2028-06-14', 'Perú'],
            ['043-2023', 'SERVICIO NACIONAL FORESTAL Y DE FAUNA SILVESTRE (SERFOR)', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE EL SERVICIO NACIONAL FORESTAL Y DE FAUNA SILVESTRE (SERFOR) Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-06-02', '2025-06-02', 'Perú'],
            ['044-2023', 'HOSPITAL NACIONAL DANIEL ALCIDES CARRIÓN', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE HOSPITAL NACIONAL DANIEL ALCIDES CARRIÓN Y LA FACULTAD DE MEDICINA HUMANA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-04-11', '2026-04-11', 'Perú'],
            ['045-2023', 'CENTRO NACIONAL DE PLANEAMIENTO ESTRATEGICO - CEPLAN', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN ENTRE EL CENTRO NACIONAL DE PLANEAMIENTO ESTRATEGICO - CEPLAN Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-08-07', '2026-08-07', 'Perú'],
            ['046-2023', 'SERVICIOS NACIONAL DE METEOROLOGÍA E HIDROLOGIA DEL PERÚ - SENAMHI', 'Otros', 'CONVENIO ESPECIFICO DE CCOPERACIÓN INTERINSTITUCIONAL ENTRE SERVICIOS NACIONAL DE METEOROLOGÍA E HIDROLOGIA DEL PERÚ - SENAMHI Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU', '2023-08-08', '2027-08-08', 'Perú'],
            ['047-2023', 'AUTORIDAD NACIONAL DEL AGUA - ANA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIIONAL DEL CENTRO DEL PERÚ Y LA AUTORIDAD NACIONAL DEL AGUA - ANA', '2023-08-09', '2027-08-09', 'Perú'],
            ['048-2023', 'UNIVERSIDAD NACIONAL DE CAÑETE', 'Universidad Nacional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA UNIVERSIDAD NACIONAL DE CAÑETE', '2023-08-31', '2028-08-31', 'Perú'],
            ['049-2023', 'UNIVERSIDAD NACIONAL SANTIAGO ANTÚÑEZ DE MAYOLO (UNASAM )', 'Universidad Nacional', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL SANTIAGO ANTÚÑEZ DE MAYOLO (UNASAM ) Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-08-31', '2028-08-31', 'Perú'],
            ['050-2023', 'UNIVERSIDAD NACIONAL HERMILIO VALDIZAN (UNHEVAL)', 'Universidad Nacional', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ  Y LA UNIVERSIDAD NACIONAL HERMILIO VALDIZAN (UNHEVAL)', '2023-08-31', '2026-08-31', 'Perú'],
            ['051-2023', 'UNIVERSIDAD PRIVADA DE HUANCAYO FRANKLIN ROOSVELT', 'Universidad Privada', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA UNIVERSIDAD PRIVADA DE HUANCAYO FRANKLIN ROOSVELT', '2023-08-31', '2026-08-31', 'Perú'],
            ['052-2023', 'COMUNIDAD CAMPESINA DE HUACRAPUQUIO', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE HUACRAPUQUIO', '2023-09-01', '2025-09-01', 'Perú'],
            ['053-2023', 'GOBIERNO REGIONAL DE JUNIN', 'Gobierno Regional', 'CONVENIO ESPECIFICO DE COOPERACION INTERINSTITUCIONAL ENTRE EL GOBIERNO REGIONAL DE JUNIN Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-09-11', '2025-09-11', 'Perú'],
            ['054-2023', 'MUNICIPALIDAD DISTRITAL DE EL CARMEN', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD DISTRITAL DE EL CARMEN', '2023-09-13', '2025-09-13', 'Perú'],
            ['055-2023', 'COMUNIDAD CAMPESINA DE HUAYAO- PROVINCIA DE CHUPACA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA COMUNIDAD CAMPESINA DE HUAYAO- PROVINCIA DE CHUPACA', '2023-09-25', '2026-09-25', 'Perú'],
            ['056-2023', 'MUNICIPALIDAD DISTRITAL DE PANCAN', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD DISTRITAL DE PANCAN', '2023-09-25', '2025-09-25', 'Perú'],
            ['057-2023', 'CALIDAD VISUAL SAC', 'Empresa Nacional', 'CONVENIO DE COOPERACION ENTRE CALIDAD VISUAL SAC Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-09-25', '2025-09-25', 'Perú'],
            ['058-2023', 'SUPERINTENDENCIA NACIONAL DE FISCALIZACION LABORAL - SUNAFIL', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA SUPERINTENDENCIA NACIONAL DE FISCALIZACION LABORAL - SUNAFIL Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-09-26', '2025-09-26', 'Perú'],
            ['059-2023', 'INSTITUTO DE EDUCACION SUPERIOR TECNOLOGICO LA OROYA', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL INSTITUTO DE EDUCACION SUPERIOR TECNOLOGICO LA OROYA', '2023-10-02', '2028-10-02', 'Perú'],
            ['060-2023', 'FUNDACION UNIVERSITARIA EUROPEA DE RELACIONES PUBLICAS - UNIVERSIDAD BARCELONA', 'Universidad Internacional', 'CONVENIO DE COLABORACION ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA FUNDACION UNIVERSITARIA EUROPEA DE RELACIONES PUBLICAS, COMO TITULAR DE LA ESCUELA SUPERIOR DE RELACIONES PUBLICAS, CENTRO ADSCRITO A LA UNIVERSIDAD BARCELONA', '2023-10-02', '2025-10-02', 'España'],
            ['061-2023', 'COMUNIDAD CAMPESINA DE CANCHAPALCA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE CANCHAPALCA', '2023-10-05', '2026-10-05', 'Perú'],
            ['062-2023', 'COMUNIDAD CAMPESINA DE TUNSO', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE TUNSO', '2023-10-05', '2026-10-05', 'Perú'],
            ['063-2023', 'COMUNIDAD CAMPESINA DE JATUN HUASI', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE JATUN HUASI', '2023-10-05', '2026-10-05', 'Perú'],
            ['064-2023', 'COMUNIDAD CAMPESINA DE POMAMANTA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE POMAMANTA', '2023-10-05', '2026-10-05', 'Perú'],
            ['065-2023', 'COMUNIDAD CAMPESINA DE RACRACALLA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE RACRACALLA', '2023-10-05', '2026-10-05', 'Perú'],
            ['066-2023', 'MUNICIPALIDAD DISTRITAL DE SAN JOSE QUERO', 'Municipalidad', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD DISTRITAL DE SAN JOSE QUERO Y LA  UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU', '2023-07-06', '2026-07-06', 'Perú'],
            ['067-2023', 'INSTITUCIÓN EDUCATIVA JUAN HILDEBRANDO GONZALES CANGAHUALA', 'Otros', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA INSTITUCIÓN EDUCATIVA JUAN HILDEBRANDO GONZALES CANGAHUALA DE LA UNION LETICIA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ FACULTAD DE CIENCIAS APLICADAS TARMA', '2023-07-06', '2026-07-06', 'Perú'],
            ['068-2023', 'INSTITUTO NACIONAL DE ESTADÍSTICA E INFORMÁTICA - INEI', 'Otros', 'CONVENIO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE EL INSTITUTO NACIONAL DE ESTADÍSTICA E INFORMÁTICA - INEI Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-08-04', '2024-08-04', 'Perú'],
            ['069-2023', 'BANCO PICHINCHA', 'Empresa Nacional', 'CONVENIO MARCO ENTRE EL BANCO PICHINCHA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-05-30', '2026-05-30', 'Perú'],
            ['070-2023', 'COMUNIDAD CAMPESINA DE UÑAS', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE  UÑAS', '2023-06-24', '2025-06-24', 'Perú'],
            ['071-2023', 'COMUNIDAD CAMPESINA DE AZAPAMPA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE  AZAPAMPA', '2023-06-24', '2025-06-24', 'Perú'],
            ['072-2023', 'COMUNIDAD CAMPESINA DE COCHAS GRANDE', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE  COCHAS GRANDE', '2023-06-24', '2025-06-24', 'Perú'],
            ['073-2023', 'COMUNIDAD CAMPESINA DE QUICHUAY', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE  QUICHUAY', '2023-06-24', '2025-06-24', 'Perú'],
            ['074-2023', 'COMUNIDAD CAMPESINA DE ISCOS', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE  ISCOS', '2023-06-24', '2025-06-24', 'Perú'],
            ['075-2023', 'COLEGIO DE POSTGRADUADOS - COLPOS', 'Universidad Internacional', 'CONVENIO ESPECÍFICO DE COOPERACION INTERINSTITUCIONAL PARA LA CREACIÓN - IMPLEMENTACIÓN DE LA MAESTRÍA EN CIENCIAS ÁREA ENTOMOLOGÍA Y ACAROLOGÍA ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y EL COLEGIO DE POSTGRADUADOS', '2023-07-19', '2028-07-19', 'México'],
            ['076-2023', 'COMUNIDAD CAMPESINA DE PUNPUNYA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE  PUNPUNYA', '2023-08-03', '2025-08-03', 'Perú'],
            ['077-2023', 'MUNICIPALIDAD DISTRITAL DE CURICACA', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD DISTRITAL DE CURICACA', '2023-08-11', '2026-08-11', 'Perú'],
            ['078-2023', 'MUNICIPALIDAD DISTRITAL DE HUAMALI', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD DISTRITAL DE HUAMALI', '2023-08-14', '2026-08-14', 'Perú'],
            ['079-2023', 'MUNICIPALIDAD DISTRITAL DE COLCABAMBA TAYACAJA HUANCAVELICA', 'Municipalidad', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD DISTRITAL DE COLCABAMBA TAYACAJA HUANCAVELICA', '2023-08-22', '2025-08-22', 'Perú'],
            ['080-2023', 'CENTRO DE INVESTIGACIONES INTERNACIONALES SAS - CEDINTER', 'Empresa Internacional', 'CONVENIO MARCO DE COOPERACIÓN ACADÉMICA E INVESTIGACIÓN ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y CENTRO DE INVESTIGACIONES INTERNACIONALES SAS - CEDINTER', '2023-09-06', '2028-09-06', 'Colombia'],
            ['081-2023', 'COLEGIO DE INGENIEROS DEL PERÚ CONSEJO DEPARTAMENTAL DE JUNIN', 'Otros', 'CONVENIO MARCO DE COOPERACIÓN INSTITUCIONAL ENTRE EL COLEGIO DE INGENIEROS DEL PERÚ CONSEJO DEPARTAMENTAL DE JUNIN Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-10-11', '2028-10-11', 'Perú'],
            ['082-2023', 'COMUNIDAD CAMPESINA DE CHAMBARÁ', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE  CHAMBARÁ', '2023-10-18', '2026-10-18', 'Perú'],
            ['083-2023', 'COMUNIDAD CAMPESINA DE CHICCHE', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE  CHICCHE', '2023-10-19', '2025-10-19', 'Perú'],
            ['084-2023', 'COMUNIDAD CAMPESINA DE CULLPAS Y COCHAS CHICO', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE  CULLPAS Y COCHAS CHICO', '2023-10-30', '2025-10-30', 'Perú'],
            ['085-2023', 'COMUNIDAD CAMPESINA DE TARMATAMBO', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE  TARMATAMBO', '2023-11-14', '2025-11-14', 'Perú'],
            ['086-2023', 'COMUNIDAD CAMPESINA DE SAN JOSE DE APATA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE  SAN JOSE DE APATA', '2023-10-30', '2025-10-30', 'Perú'],
            ['087-2023', 'COMUNIDAD CAMPESINA DE SANTA CRUZ DE RANRA - JARPA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE  SANTA CRUZ DE RANRA - JARPA', '2023-11-18', '2025-11-18', 'Perú'],
            ['088-2023', 'COMUNIDAD CAMPESINA DE MISQUIPATA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE  MISQUIPATA', '2023-11-18', '2025-11-18', 'Perú'],
            ['089-2023', 'COMUNIDAD CAMPESINA SAN JUAN DE JARPA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA SAN JUAN DE JARPA', '2023-11-18', '2025-11-18', 'Perú'],
            ['090-2023', 'COMUNIDAD CAMPESINA DE SANTA ROSA DE HUACRAMASANA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE SANTA ROSA DE HUACRAMASANA', '2023-11-22', '2026-11-22', 'Perú'],
            ['091-2023', 'COMUNIDAD CAMPESINA DE SANTA MAGDALENA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE SANTA MAGDALENA', '2023-11-29', '2026-11-29', 'Perú'],
            ['092-2023', 'COMUNIDAD CAMPESINA DE CONCHO', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE CONCHO', '2023-11-28', '2025-11-28', 'Perú'],
            ['093-2023', 'COMUNIDAD CAMPESINA DE HUERTAS', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE HUERTAS', '2023-11-28', '2025-11-28', 'Perú'],
            ['094-2023', 'COMUNIDAD CAMPESINA DE HUARIPAMPA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE HUARIPAMPA', '2023-11-28', '2025-11-28', 'Perú'],
            ['095-2023', 'COMUNIDAD CAMPESINA DE APATA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE APATA', '2023-11-28', '2025-11-28', 'Perú'],
            ['096-2023', 'COMUNIDAD CAMPESINA DE CANCHAYLLO', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE CANCHAYLLO', '2023-11-28', '2025-11-28', 'Perú'],
            ['097-2023', 'COMUNIDAD CAMPESINA DE CURICACA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE CURICACA', '2023-11-28', '2025-11-28', 'Perú'],
            ['098-2023', 'COMUNIDAD CAMPESINA DE PANCAN', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE PANCAN', '2023-11-28', '2025-11-28', 'Perú'],
            ['099-2023', 'COMUNIDAD CAMPESINA DE HUALA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE HUALA', '2023-11-28', '2025-11-28', 'Perú'],
            ['100-2023', 'COMUNIDAD CAMPESINA DE MOLINOS', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE MOLINOS', '2023-11-28', '2025-11-28', 'Perú'],
            ['101-2023', 'COMUNIDAD CAMPESINA DE MARCO - JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE MARCO - JAUJA', '2023-11-28', '2025-11-28', 'Perú'],
            ['102-2023', 'COMUNIDAD CAMPESINA DE HUASQUICHA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE HUASQUICHA', '2023-11-28', '2025-11-28', 'Perú'],
            ['103-2023', 'COMUNIDAD CAMPESINA DE SAUSA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE SAUSA', '2023-11-28', '2025-11-28', 'Perú'],
            ['104-2023', 'COMUNIDAD CAMPESINA DE ULLUSCA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE ULLUSCA', '2023-11-28', '2025-11-28', 'Perú'],
            ['105-2023', 'COMUNIDAD CAMPESINA DE LLOCLLAPAMPA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE LLOCLLAPAMPA', '2023-11-28', '2025-11-28', 'Perú'],
            ['106-2023', 'COMUNIDAD CAMPESINA DE SALLAHUACHAC', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE SALLAHUACHAC', '2023-11-28', '2025-11-28', 'Perú'],
            ['107-2023', 'COMUNIDAD CAMPESINA DE MATAGRANDE', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE MATAGRANDE', '2023-11-28', '2025-11-28', 'Perú'],
            ['108-2023', 'COMUNIDAD CAMPESINA DE CHOCON - JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE CHOCON - JAUJA', '2023-11-28', '2025-11-28', 'Perú'],
            ['109-2023', 'COMUNIDAD CAMPESINA DE MATACHICO', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE MATACHICO', '2023-11-28', '2025-11-28', 'Perú'],
            ['110-2023', 'COMUNIDAD CAMPESINA DE CASABLANCA - JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE CASABLANCA - JAUJA', '2023-11-28', '2025-11-28', 'Perú'],
            ['111-2023', 'COMUNIDAD CAMPESINA DE TINGO - JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE TINGO - JAUJA', '2023-11-28', '2025-11-28', 'Perú'],
            ['112-2023', 'COMUNIDAD CAMPESINA DE TINGO PACCHA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE TINGO PACCHA', '2023-11-28', '2025-11-28', 'Perú'],
            ['113-2023', 'COMUNIDAD CAMPESINA DE SAN JOSE', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE SAN JOSE', '2023-11-28', '2025-11-28', 'Perú'],
            ['114-2023', 'COMUNIDAD CAMPESINA DE PACHASCUCHO', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE PACHASCUCHO', '2023-11-28', '2025-11-28', 'Perú'],
            ['115-2023', 'UNIVERSIDAD NACIONAL JOSLÉ MARÍA ARGUEDAS', 'Universidad Nacional', 'CONVENIO ESPECÍFICO DE MOVILIDAD ESTUDIANTIL, DOCENTE Y ADMINISTRATIVO CELEBRADO ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA UNIVERSIDAD NACIONAL JOSLÉ MARÍA ARGUEDAS', '2023-09-12', '2027-09-12', 'Perú'],
            ['116-2023', 'COMUNIDAD CAMPESINA DE LLACUARIPAMPA - JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE LLACUARIPAMPA - JAUJA', '2023-11-28', '2025-11-28', 'Perú'],
            ['117-2023', 'COMUNIDAD CAMPESINA DE CAYAO MISARRURSHA - JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE CAYAO MISARRURSHA - JAUJA', '2023-12-28', '2025-12-28', 'Perú'],
            ['118-2023', 'COMUNIDAD CAMPESINA DE YAULI JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE YAULI JAUJA', '2023-12-28', '2025-12-28', 'Perú'],
            ['119-2023', 'COMUNIDAD CAMPESINA DE RICRAN JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE RICRAN JAUJA', '2023-12-28', '2025-12-28', 'Perú'],
            ['120-2023', 'COMUNIDAD CAMPESINA DE CURIMARCA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE CURIMARCA', '2023-12-28', '2025-12-28', 'Perú'],
            ['121-2023', 'COMUNIDAD CAMPESINA DE PACA - JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE PACA - JAUJA', '2023-12-28', '2025-12-28', 'Perú'],
            ['122-2023', 'COMUNIDAD CAMPESINA DE ANDAMARCA - HUALHUAS - JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE ANDAMARCA - HUALHUAS - JAUJA', '2023-12-28', '2025-12-28', 'Perú'],
            ['123-2023', 'COMUNIDAD CAMPESINA DE ANDAMARCA - CURIS - JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE ANDAMARCA - CURIS - JAUJA', '2023-12-28', '2025-12-28', 'Perú'],
            ['124-2023', 'COMUNIDAD CAMPESINA DE AYAS- JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE AYAS- JAUJA', '2023-12-28', '2025-12-28', 'Perú'],
            ['125-2023', 'COMUNIDAD CAMPESINA DE JANJAILLO - JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE JANJAILLO - JAUJA', '2023-12-28', '2025-12-28', 'Perú'],
            ['126-2023', 'COMUNIDAD CAMPESINA DE MUQUI - JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE MUQUI - JAUJA', '2023-12-28', '2025-12-28', 'Perú'],
            ['127-2023', 'COMUNIDAD CAMPESINA DE JULCAN - JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE JULCAN - JAUJA', '2023-12-28', '2025-12-28', 'Perú'],
            ['128-2023', 'COMUNIDAD DE LLACUAS HUACHAC - MANZANARES - CONCEPCIÓN', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD (NATIVA O CAMPESINA) DE LLACUAS HUACHAC - MANZANARES - CONCEPCIÓN', '2023-12-29', '2025-12-29', 'Perú'],
            ['129-2023', 'COMUNIDAD CAMPESINA DE PACCHA - JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE PACCHA - JAUJA', '2023-12-28', '2025-12-28', 'Perú'],
            ['130-2023', 'COMUNIDAD CAMPESINA DE HUANCAS JAUJA', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA COMUNIDAD CAMPESINA DE HUANCAS JAUJA', '2023-12-28', '2025-12-28', 'Perú'],
            ['131-2023', 'INSTITUCIÓN EDUCATIVA LA VICTORIA - EL TAMBO', 'Otros', 'CONVENIO ESPECÍFICO ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ -FACULTAD DE TRABAJO SOCIAL Y LA INSTITUCIÓN EDUCATIVA LA VICTORIA - EL TAMBO', '2023-09-01', '2028-09-01', 'Perú'],
            ['132-2023', 'INSTITUTO NACIONAL PENITENCIARIO - INPE', 'Otros', 'CONVENIO ESPECÍFICO DE COOPERACIÓN ENTRE LA OFICINA REGIONAL CENTRO HUANCAYO Y LA FACULTAD DE TRABAJO SOCIAL DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2023-07-14', '2027-07-14', 'Perú'],
        ];

        foreach ($datos as $fila) {
            
            $nombreInstitucion = strtoupper($fila[1]);
            $tipoInstitucion = $fila[2];
            $pais = $fila[6];

            // Agrupar comunidades
            if (str_contains($nombreInstitucion, 'COMUNIDAD')) {
                $nombreInstitucion = 'COMUNIDADES CAMPESINAS Y NATIVAS';
                $tipoInstitucion = 'Comunidad';
            }

            // Buscar o crear la institución
            $institucion = Institution::firstOrCreate(
                ['name' => $nombreInstitucion],
                ['country' => $pais, 'type' => $tipoInstitucion]
            );

            // Asignar el ID del tipo de convenio
            $nombreLargo = strtoupper($fila[3]);
            
            if (str_contains($nombreLargo, 'MEMORANDO')) {
                $tipoId = $tipos['memorando']->id;
            } elseif (str_contains($nombreLargo, 'ESPECIFICO') || str_contains($nombreLargo, 'ESPECÍFICO') || str_contains($nombreLargo, 'ADENDA N°01')) {
                $tipoId = $tipos['especifico']->id; 
            } else {
                $tipoId = $tipos['marco']->id;
            }

            // Crear el convenio
            // 1. Creamos el convenio y lo guardamos en una variable
            $agreement = Agreement::create([
                'title' => $fila[0],
                'name' => $fila[3],
                'resolution_number' => $fila[0],
                'institution_id' => $institucion->id,
                'agreement_type_id' => $tipoId, 
                'start_date' => $fila[4],
                'end_date' => $fila[5],
                'status' => 'Vigente'
            ]);

            // 2. Lógica actualizada para buscar en subcarpetas por año
            $codigo = $fila[0]; // Ej: '001-2024'
            
            // Extraemos los últimos 4 caracteres del código para obtener el año (ej: '2024')
            $anio = substr($codigo, -4); 
            
            // Armamos la ruta incluyendo la carpeta del año
            $rutaRelativa = "convenios/{$anio}/{$codigo}.pdf"; 

            // Verificamos si existe y lo guardamos
            if (\Illuminate\Support\Facades\Storage::disk('public')->exists($rutaRelativa)) {
                $agreement->documents()->create([
                    'name' => 'Doc - ' . ($agreement->resolution_number ?? $agreement->title),
                    'file_path' => $rutaRelativa,
                    'extension' => 'pdf'
                ]);
            }
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}