<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Agreement;
use App\Models\Institution;
use App\Models\AgreementType;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class Convenios2019Seeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        $tipos = [
            'marco' => AgreementType::firstOrCreate(['name' => 'Convenio Marco']),
            'especifico' => AgreementType::firstOrCreate(['name' => 'Convenio Específico']),
            'memorando' => AgreementType::firstOrCreate(['name' => 'Memorando de Entendimiento']),
            'adenda' => AgreementType::firstOrCreate(['name' => 'Adenda']),
        ];
        
        $datos = [
            ['001-2019', 'MINISTERIO DE EDUCACIÓN', 'Sector Público', 'CONVENIO DE COLABORACIÓN INTERINSTITUCIONAL ENTRE EL MINISTERIO DE EDUCACIÓN Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2019-02-01', '2019-12-31', 'Perú'],
            ['002-2019', 'LIBRERÍA MIBOOK', 'Empresa Nacional', 'CONVENIO DE CRÉDITO BIBLIOGRÁFICO DOCENTE ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA LIBRERÍA MIBOOK', '2019-02-21', '2022-02-21', 'Perú'],
            ['003-2019', 'MINISTERIO DE ENERGÍA Y MINAS', 'Sector Público', 'CONVENIO MARCO DE COLABORACIÓN INTERINSTITUCIONAL ENTRE EL MINISTERIO DE ENERGÍA Y MINAS Y LA UNCP', '2019-02-26', '2022-02-26', 'Perú'],
            ['004-2019', 'RED DE SALUD AYACUCHO NORTE', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE LA RED DE SALUD AYACUCHO NORTE Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ – HUANCAYO – JUNÍN – FACULTAD DE MEDICINA HUMANA', '2019-03-25', '2022-03-25', 'Perú'],
            ['005-2019', 'RED DE SALUD AYACUCHO NORTE', 'Salud', 'CONVENIO ESPECÍFICO DE COOPERACIÓN DOCENTE ASISTENCIAL ENTRE LA RED DE SALUD AYACUCHO NORTE Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ – HUANCAYO – JUNÍN – FACULTAD DE ENFERMERÍA', '2019-03-25', '2022-03-25', 'Perú'],
            ['006-2019', 'UNIVERSIDAD DE CARTAGENA', 'Universidad Internacional', 'CONVENIO MARCO DE COOPERACIÓN ACADÉMICA CELEBRADO ENTRE LA UNIVERSIDAD DE CARTAGENA - COLOMBIA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2019-03-01', '2023-03-01', 'Colombia'],
            ['007-2019', 'UNIVERSIDAD DE CARTAGENA', 'Universidad Internacional', 'CONVENIO ESPECÍFICO DE MOVILIDAD ENTRE LA UNCP Y LA UNIVERSIDAD DE CARTAGENA', '2019-03-01', '2022-03-01', 'Colombia'],
            ['008-2019', 'FRENTE DE DEFENSA Y DESARROLLO DEL DISTRITO DE SAN JOSÉ DE QUERO', 'Otros', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y EL FRENTE DE DEFENSA Y DESARROLLO DEL DISTRITO DE SAN JOSÉ DE QUERO, PROVINCIA DE CONCEPCIÓN, JUNIN', '2019-04-01', '2024-04-01', 'Perú'],
            ['009-2019', 'UNIVERSIDAD RICARDO PALMA', 'Educación', 'CONVENIO MARCO DE COOPERACIÓN ACADÉMICA, CULTURAL, CIENTÍFICA Y TECNOLOGICA ENTRE LA UNIVERSIDAD RICARDO PALMA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2019-02-25', '2024-02-25', 'Perú'],
            ['010-2019', 'MUNICIPALIDAD PROVINCIAL DE JAUJA', 'Sector Público', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD PROVINCIAL DE JAUJA', '2019-04-24', '2022-04-24', 'Perú'],
            ['011-2019', 'MUNICIPALIDAD DISTRITAL DE CARHUACALLANGA', 'Sector Público', 'CONVENIO MARCO DE COOPERACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y MUNICIPALIDAD DISTRITAL CARHUACALLANGA', '2019-04-16', '2023-04-16', 'Perú'],
            ['012-2019', 'UNIVERSIDAD PRIVADA JUAN PABLO II S.A.C.', 'Educación', 'CONVENIO MARCO DE COLABORACIÓN INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD PRIVADA JUAN PABLO II S.A.C. Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ', '2019-04-08', '2021-04-08', 'Perú'],
            ['013-2019', 'PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU', 'Educación', 'CONVENIO ESPECIFICO DE COOPERACION ENTRE LA PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU', '2019-03-27', '2020-05-31', 'Perú'],
            ['014-2019', 'PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU', 'Educación', 'CONVENIO ESPECIFICO DE COOPERACION ENTRE LA PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU', '2019-03-27', '2022-03-27', 'Perú'],
            ['015-2019', 'LAURENTIAN UNIVERSITY', 'Universidad Internacional', 'MEMORANDO DE ACUERDO ENTRE LA UNCP Y LAURENTIA UNIVERSITY', '2019-05-09', '2021-05-09', 'Canadá'],
            ['016-2019', 'UNIVERSIDAD RICARDO PALMA', 'Educación', 'CONVENIO ESPECIFICO DE MOVILIDAD ESTUDIANTIL DE GRADO ENTRE LA UNIVERSIDAD RICARDO PALMA Y LA UNCP', '2019-02-25', '2024-02-25', 'Perú'],
            ['017-2019', 'CENTRO ECUNEMICO DE PROMOCION Y ACCION SOCIAL CENTRO CEDEPAS', 'Otros', 'CONVENIO DE ASOCIACION ENTRE LA UNCP Y EL CENTRO ECUNEMICO DE PROMOCION Y ACCION SOCIAL CENTRO', '2019-05-08', '2021-05-08', 'Perú'],
            ['018-2019', 'UNIVERSIDAD DE PURDUE', 'Universidad Internacional', 'ACUERDO MAESTRO DE ALIANZA ESTRETEGICA ENTRE LA UNCP Y LA UNIVERSIDAD PURDUE', '2019-04-25', '2029-12-31', 'Estados Unidos'],
            ['019-2019', 'UNIVERSIDAD NACIONAL DANIEL ALCIDES CARRION', 'Educación', 'CONVENIO MARCO DE COLABORACION ENTRE LA UNIVERSIDAD NACIONAL DANIEL ALCIDES CARRION - UNDAC Y LA UNCP', '2019-04-24', '2024-04-24', 'Perú'],
            ['020-2019', 'UNIVERSIDAD NACIONAL DANIEL ALCIDES CARRION', 'Educación', 'CONVENIO ESPECIFICO DE COOPERACION ENTRE LA UNIVERSIDAD NACIONAL DANIEL ALCIDES CARRION Y LA UNCP', '2019-04-24', '2024-04-24', 'Perú'],
            ['021-2019', 'MUNICIPALIDAD DISTRITAL DE POMACANCHA', 'Sector Público', 'CONVENIO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UCP Y LA MUNICIPALIDAD DISTRITAL DE POMACANCHA', '2019-04-30', '2020-12-31', 'Perú'],
            ['022-2019', 'INSTITUTO DE EDUCACION SUPERIOR TECNOLOGICO ANDRES CACERES DORREGARAY', 'Educación', 'CONVENIO ENTRE LA UNCP Y EL INSTITUTO DE EDUCACION SUPERIOR TECNOLOGICO ANDRES CACERES DORREGARAY DE SAN AGUSTIN DE CAJAS', '2019-05-31', '2021-05-31', 'Perú'],
            ['023-2019', 'MUNICIPALIDAD DE RIO NEGRO', 'Sector Público', 'CONVENIO MACRO DE COOPERACION INTERINSTITUICONAL ENTRE LA MUNICIPALIDAD DE RIO NEGRO Y LA UNCP', '2019-05-23', '2022-05-23', 'Perú'],
            ['024-2019', 'EMPRESA MANAGE YOUR PROCESS SAC', 'Empresa Nacional', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNCP Y LA EMPRESA MANAGE YOUR PROCESS SAC', '2019-06-17', '2021-06-17', 'Perú'],
            ['025-2019', 'MUNICIPALIDAD DISTRITAL DE COVIRIALI', 'Sector Público', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD DISTRITAL DE COVIRIALI Y LA UNCP', '2019-04-30', '2022-04-30', 'Perú'],
            ['026-2019', 'MUNICIPALIDAD DISTRITAL DE LLAYLLA', 'Sector Público', 'CONVENIO MARCO DE COOPERACION INTERINSTICIONAL ENTRE LA MUNICIPALIDAD DISTRITAL DE LLAYLLA Y LA UNCP', '2019-04-30', '2022-04-30', 'Perú'],
            ['027-2019', 'MUNICIPALIDAD DISTRITAL DE SICAYA', 'Sector Público', 'CONVENIO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNCP Y LA MUNICIPALIDAD DISTRITAL DE SICAYA', '2019-06-14', '2022-06-14', 'Perú'],
            ['028-2019', 'SERVICIO DE ADMINISTRACION TRIBUTARIA DE HUANCAYO - SATH', 'Sector Público', 'CONVENIO INTERINSTITUCIONAL PARA LA REALIZACION DE EXPERIENCIAS FORMATIVAS EN SITUACIONES REALES DE TRABAJO ENTRE LA UNCO Y SERVICIO DE ADMINISTRACION TRIBUTARIA DE HUANCAYO - SATH', '2019-06-21', null, 'Perú'],
            ['029-2019', 'ORGANIZACIÓN INTERNACIONAL FILOSOFICA NUEVA ACROPOLIS HUANCAYO', 'Otros', 'CONVENIO DE ALIANZA ESTRATEGICA ENTRE LA UNCP Y LA ORGANIZACIÓN INTERNACIONAL FILOSOFICA "NUEVA ACROPOLIS" HUANCAYO', '2019-06-28', '2020-06-28', 'Perú'],
            ['030-2019', 'MUNICIPALIDAD DISTRITAL DE RIO TAMBO', 'Sector Público', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD DISTRITAL DE RIO TAMBO Y LA UNCP', '2019-04-30', '2022-04-30', 'Perú'],
            ['031-2019', 'GOBIERNO REGIONAL JUNIN', 'Sector Público', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE EL GOBIERNO REGIONAL JUNIN Y LA UNCP', '2019-05-07', '2023-05-07', 'Perú'],
            ['032-2019', 'DIRECCION REGIONAL DE EDUCACION JUNIN', 'Sector Público', 'CONVENIO ESPECIFICO DE COOPERACION INTERINSTITUCIONAL ENTRE EL GOBIERNO REGIONAL JUNIN Y LA UNCP, PARA LA ACTUALIZACION E IMPLEMENTACION PILOTO DE CURRICULO REGIONAL DE EDUCACION BASICA - REGION JUNIN', '2019-05-13', '2020-03-13', 'Perú'],
            ['033-2019', 'FUDEC', 'Otros', 'CONVENIO ESPECIFICO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNCP Y FUDEC SOBRE EL CENTRO EXPERIMENTAL Y PRODUCCION "CASARACRA"', '2018-10-29', '2021-10-29', 'Perú'],
            ['034-2019', 'RED ASISTENCIAL APURIMAC-ESSALUD', 'Salud', 'CONVENIO ESPECIFICO ENTRE LA RED ASISTENCIAL APURIMAC-ESSALUD Y DE LA FACULTAD DE MEDICINA HUMANA DE LA UNCP', '2019-03-29', null, 'Perú'],
            ['035-2019', 'MUNICIPALIDAD DISTRITAL DE HUALHUAS', 'Sector Público', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ Y LA MUNICIPALIDAD DISTRITAL DE HUALHUAS', '2019-06-28', '2024-06-28', 'Perú'],
            ['036-2019', 'HOSPITAL REGIONAL DOCENTE MATERNO INFANTIL EL CARMEN', 'Salud', 'RENOVACION CONVENIO ESPECICO DE COOPERACION DOCENTE ASISTENCIAL ENTRE EL HOSPITAL REGIONAL DOCENTE MATERNO INFANTIL "EL CARMEN" Y LA UNCP - FACULTAD DE MEDICINA HUMANA', '2019-02-13', '2022-02-13', 'Perú'],
            ['037-2019', 'PROGRAMA REFORMA DE VIDA', 'Salud', 'ALIANZA DE INTERVENCION: EJECUCION DEL PROGRAMA DE REFORMA DE VIDA', '2019-07-19', '2020-07-19', 'Perú'],
            ['038-2019', 'CALIDAD VISUAL SAC', 'Empresa Nacional', 'CONVENIO DE COOPERACION ENTRE CALIDAD VISUAL SAC Y LA UNCP', '2019-07-22', '2020-07-22', 'Perú'],
            ['039-2019', 'PROINVERSION', 'Sector Público', 'CONVENIO DE ASISTENCIA TECNICA EN LA MODALIDAD DE ASOSORIA ENTRE PROINVERSION Y LA UNCP', '2019-07-31', '2021-07-31', 'Perú'],
            ['040-2019', 'MUNICIPALIDAD DISTRITAL DE MAZAMARI', 'Sector Público', 'CONVENIO DE COOPERACION INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD DISTRITAL DE MAZAMARI Y LA UNCP', '2019-04-30', '2022-04-30', 'Perú'],
            ['041-2019', 'MUNICIPALIDAD DISTRITAL DE CURICACA', 'Sector Público', 'CONVENIO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNCP Y LA MUNICIPALIDAD DISTRITAL DE CURICACA', '2019-08-19', '2020-12-31', 'Perú'],
            ['042-2019', 'VULCANO TECNOLOGIA APLICADA E.I.R.L', 'Empresa Nacional', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNCP Y VULCANO TECNOLOGIA APLICADA E.I.R.L', '2019-08-05', '2024-08-05', 'Perú'],
            ['043-2019', 'I.E. PUBLICA FRANCISCANA PADRE PIO SAROBE', 'Educación', 'CONVENIO ESPECIFICO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNCP - FACULTAD DE TRABAJO SOCIAL Y LA I.E. PUBLICA "FRANCISCANA PADRE PIO SAROBE".', '2018-11-14', '2021-11-14', 'Perú'],
            ['044-2019', 'INSTITUTO DE EDUCACION SUPERIOR TECNOLOGICO PUBLICO ASHANINKA', 'Educación', 'ADENDA AL CONVENIO ESPECIFICO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNCP Y EL INSTITUTO DE EDUCACION SUPERIOR TECNOLOGICO PUBLICO ASHANINKA', null, null, 'Perú'],
            ['045-2019', 'UNIDAD EJECUTORA Nº 118 MEJORAMIENTO DE LA CALIDAD EDUCACION BASICA Y SUPERIOR', 'Sector Público', 'CONVENIO DE COOPERACION INTERINSTITUCIOANL ENTRE LA UNIDAD EJECUTORA Nº 118 MEJORAMIENTO DE LA CALIDAD EDUCACION BASICA Y SUPERIOR Y LA UNCP', null, null, 'Perú'],
            ['046-2019', 'MINISTERIO DE ENERGIA Y MINAS - DIRECCION GENERAL DE EFICIENCIA ENERGETICA', 'Sector Público', 'CONVENIO DE COOPERACION INTERINSTITUCIONAL PARA LA DONACION DE UN PROYECTO PILOTO FOTOVOLTAICO', '2018-11-26', '2020-11-26', 'Perú'],
            ['047-2019', 'MUNICIPALIDAD PROVINCIAL DE SATIPO', 'Sector Público', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA MUNICIPALIDAD PROVINCIAL DE SATIPO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU', '2019-04-30', '2022-04-30', 'Perú'],
            ['048-2019', 'UNIVERSIDAD DE CHILE', 'Universidad Internacional', 'CONVENIO MARCO ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA FACULTAD DE CIENCIAS DE LA UNIVERSIDAD DE CHILE', '2019-07-26', '2024-07-26', 'Chile'],
            ['049-2019', 'MUNICIPALIDAD DISTRITAL DE HUALHUAS', 'Sector Público', 'CONVENIO ESPECIFICO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD MACIONAL DEL CENTRO DEL PERU Y LA MUNICIPALIDAD DISTRITAL DE HUALHUAS DE LA PROVINCIA DE HUANCAYO', '2019-08-01', '2021-08-01', 'Perú'],
            ['050-2019', 'SAN CRISTOBAL LIBROS SAC', 'Empresa Nacional', 'CONVENIO DE ASISTENCIA COMERCIAL ENTRE SAN CRISTOBAL LIBROS SAC Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU', '2019-09-24', '2022-09-24', 'Perú'],
            ['051-2019', 'UNIVERSIDAD PERUANA LOS ANDES', 'Educación', 'CONVENIO ESPECIFICO DE COOPERACION  INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU - FACULTAD DE TRABAJO SOCIAL Y LA UNIVERSIDAD PERUANA LOS ANDES - UPLA', '2019-01-11', '2022-01-11', 'Perú'],
            ['052-2019', 'MUNICIPALIDAD DE CHONGOS ALTO', 'Sector Público', 'CONVENIO ESPECIFICO DE COOPERACION  INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA MUNICIPALIDAD DE CHONGOS ALTO DE LA PROVINCIA DE HUANCAYO', '2019-08-31', '2021-08-31', 'Perú'],
            ['053-2019', 'EMPRESA SIERRA POLI S.A.C', 'Empresa Nacional', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA EMPRESA SIERRA POLI S.A.C', '2019-10-10', '2022-10-10', 'Perú'],
            ['054-2019', 'COMUNIDAD CAMPESINA DE ACOPALCA', 'Otros', 'CONVENIO ESPECIFICO DE COOPERACION  INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y COMUNIDAD CAMPESINA DE ACOPALCA DE LA PROVINCIA DE HUANCAYO', '2019-08-26', '2021-08-26', 'Perú'],
            ['055-2019', 'MUNICIPALIDAD DE PUCARA', 'Sector Público', 'CONVENIO ESPECIFICO DE COOPERACION  INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA MUNICIPALIDAD DE PUCARA DE LA PROVINCIA DE HUANCAYO', '2019-10-21', '2021-10-21', 'Perú'],
            ['056-2019', 'ORGANISMO DE SUPERVISION DE LOS RECURSOS FORESTALES Y DE FAUNA SILVESTRE - OSINFOR', 'Sector Público', 'CONVENIO MARCO DE COOPERACION INTERINSTITUCIONAL ENTRE EL ORGANISMO DE SUPERVISION DE LOS RECURSOS FORESTALES Y DE FAUNA SILVESTRE - OSINFOR Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU - UNCP', '2019-09-23', '2022-09-23', 'Perú'],
            ['057-2019', 'ORGANISMO DE SUPERVISION DE LOS RECURSOS FORESTALES Y DE FAUNA SILVESTRE - OSINFOR', 'Sector Público', 'CONVENIO ESPECIFICO DE COOPERACION INTERINSTITUCIONAL ENTRE EL ORGANISMO DE SUPERVISION DE LOS RECURSOS FORESTALES Y DE FAUNA SILVESTRE - OSINFOR Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU - UNCP', '2019-09-23', '2022-09-23', 'Perú'],
            ['058-2019', 'BANCO PICHINCHA', 'Empresa Nacional', 'CONVENIO MARCO ENTRE EL BANCO PICHINCHA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU', '2019-11-14', '2022-11-14', 'Perú'],
            ['059-2019', 'COMANDO DE SALUD DEL EJERCITO', 'Salud', 'CONVENIO ESPECIFICO DE COOPERACION DOCENTE ASISTENCIAL, INVESTIGACION Y SERVICIOS ENTRE EL COMANDO DE SALUD DEL EJERCITO Y LA UNCP - FACULTAD DE MEDICINA HUMANA', '2019-11-08', '2020-11-08', 'Perú'],
            ['060-2019', 'CORPORACION ANDINA DE FOMENTO', 'Otros', 'ACUERDO MARCO DE COLABORACION ENTRE LA CORPORACION ANDINA DE FOMENTO Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU', '2019-11-11', '2022-11-11', 'Internacional'],
            ['061-2019', 'CORPORACION ANDINA DE FOMENTO', 'Otros', 'CONVENIO MARCO ENTRE EL BANCO PICHINCHA Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU', '2019-11-11', '2022-11-11', 'Internacional'],
            ['062-2019', 'SERVICIOS EDUCATIVOS PROMOCION Y APOYO RURAL - SEPAR', 'Otros', 'CONVENIO INTERINSTITUCIONAL PARA EL DEPOSITO Y CUSTODIA DE COLECTA ENTOMOLOGICA ENTRE SERVICIOS EDUCATIVOS PROMOCION Y APOYO RURAL - SEPAR Y LA FACULTAD DE CIENCIAS FORESTALES Y DEL AMBIENTE DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU', '2019-11-11', '2022-11-11', 'Perú'],
            ['063-2019', 'SERVICIOS EDUCATIVOS PROMOCION Y APOYO RURAL - SEPAR', 'Otros', 'CONVENIO INTERINSTITUCIONAL PARA EL DEPOSITO Y CUSTODIA DE COLECTA ENTOMOLOGICA ENTRE SERVICIOS EDUCATIVOS PROMOCION Y APOYO RURAL - SEPAR Y LA FACULTAD DE AGRONOMIA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU', '2019-11-11', '2022-11-11', 'Perú'],
            ['064-2019', 'ASOCIACION DE PRODUCTORES AGROPECUARIOS HEROINAS TOLEDO', 'Otros', 'CONVENIO INTERINSTITUCIONAL ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA ASOCIACION DE PRODUCTORES AGROPECUARIOS HEROINAS TOLEDO', '2019-11-11', '2022-11-11', 'Perú'],
            ['065-2019', 'EMPRESA SIERRA POLI SAC', 'Empresa Nacional', 'CONVENIO ESPECIFICO DE COLABORACION ENTRE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU Y LA EMPRESA SIERRA POLI SAC', '2019-11-11', '2022-11-11', 'Perú'],
            ['066-2019', 'HOSPITAL DEPARTAMENTAL DE HUANCAVELICA', 'Salud', 'CONVENIO ESPECIFICO DE COOPERACION DOCENTE ASISTENCIAL ENTRE EL HOSPITAL DEPARTAMENTAL DE HUANCAVELICA Y LA FACULTAD DE MEDICINA HUMANA DE LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERU', '2019-12-13', '2022-12-13', 'Perú'],
            ['067-2019', 'ACTA DE NEGOCIACION Y CONCERTACION DE COMPROMISOS', 'Otros', 'ACTA DE NEGOCIACION Y CONCERTACION DE COMPROMISOS', '2019-11-18', null, 'Perú'],
            ['068-2019', 'MINISTERIO DE EDUCACIÓN', 'Sector Público', 'ADENDA N° 001 AL CONVENIO N° 004-209-MINEDU "CONVENIO DE COLABORACIÓN INTERINSTITUCIONAL ENTRE EL MINISTERIO D EDUCACIÓN Y LA UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ"', '2019-02-01', '2019-12-31', 'Perú'],
        ];

        foreach ($datos as $fila) {
            $nombreInstitucion = strtoupper($fila[1]);
            $tipoEstandarizado = $fila[2]; 
            $pais = $fila[6];

            $institucion = Institution::firstOrCreate(
                ['name' => $nombreInstitucion],
                ['country' => $pais, 'type' => $tipoEstandarizado]
            );

            $nombreLargo = strtoupper($fila[3]);
            
            // Asignación de tipo de convenio
            if (str_contains($nombreLargo, 'MEMORANDO') || str_contains($nombreLargo, 'ACTA')) {
                $tipoId = $tipos['memorando']->id;
            } elseif (str_contains($nombreLargo, 'ADENDA')) {
                $tipoId = $tipos['adenda']->id;
            } elseif (str_contains($nombreLargo, 'ESPECIFICO') || str_contains($nombreLargo, 'ESPECÍFICO') || str_contains($nombreLargo, 'PROTOCOLO') || str_contains($nombreLargo, 'CONTRATO')) {
                $tipoId = $tipos['especifico']->id; 
            } else {
                $tipoId = $tipos['marco']->id; // Asume Marco por defecto si no es específico/memorando/adenda
            }

            $agreement = Agreement::firstOrCreate(
                ['resolution_number' => $fila[0]],
                [
                'title' => $fila[0],
                'name' => $fila[3],
                'resolution_number' => $fila[0],
                'institution_id' => $institucion->id,
                'agreement_type_id' => $tipoId, 
                'start_date' => $fila[4],
                'end_date' => $fila[5],
                'status' => 'Vigente'
            ]);

            $codigo = $fila[0];
            $anio = substr($codigo, -4); 
            $rutaRelativa = "convenios/{$anio}/{$codigo}.pdf"; 

            if (Storage::disk('public')->exists($rutaRelativa)) {
                $agreement->documents()->firstOrCreate(
                    ['file_path' => $rutaRelativa],
                    [
                    'name' => 'Doc - ' . ($agreement->resolution_number ?? $agreement->title),
                    'file_path' => $rutaRelativa,
                    'extension' => 'pdf'
                ]);
            }
        }
        
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}